<div>
                                        <p class="MsoNoSpacing" style="text-align:justify"><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Hướng dẫn thanh toán </span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1. PHƯƠNG THỨC GIAO HÀNG - TRẢ TIỀN MẶT:</span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Phương thức Giao hàng - Trả tiền mặt chỉ áp dụng đối với những khu vực chúng tôi hỗ trợ giao nhận miễn phí (tham khảo thêm <u>chính sách giao nhận</u>) hoặc trả tiền mua hàng trực tiếp tại Công ty TNHH SX &amp; TM WEAN</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;2. PHƯƠNG THỨC THANH TOÁN TRƯỚC: </span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Chuyển tiền, chuyển khoản, thanh toán trực tiếp bằng tiền mặt <span style="mso-spacerun:yes">&nbsp;</span>hoặc qua thẻ tại văn phòng của chúng tôi</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">a. Chuyển tiền/chuyển khoản:</span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Áp dụng cho khách <span style="mso-spacerun:yes">&nbsp;</span>hàng <span style="mso-spacerun:yes">&nbsp;</span>ngoài khu vực hỗ trợ giao nhận miễn phí và khách hàng có nhu cầu sử dụng phương thức thanh <span style="mso-spacerun:yes">&nbsp;</span>toán <span style="mso-spacerun:yes">&nbsp;</span>này</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify">&nbsp;</p>
                                        <table border="0" style="margin: 0px; padding: 0px; border-collapse: collapse; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; width: 890px;text-align: center; float: left;" class="thanh">
                                            <tbody style="margin: 0px; padding: 0px;">
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img style="margin: 0px; padding: 0px; border: 0px none;" alt="vietcom" src="http://congtynem.com/vi/public/files/editor-upload/vietcom.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span></span></strong></td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                            </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; font-size: 12pt; line-height: 18.3999996185303px; font-family: 'Times New Roman', serif;">0381 000 415 899</span></strong></span></strong></td>
                                                </tr>
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img style="margin: 0px; padding: 0px; border: 0px none;" alt="acb" src="http://congtynem.com/vi/public/files/editor-upload/acb.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;">
                                                        <p style="margin: 0px; padding: 0px; line-height: 1.3em;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                                </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span></span></strong></span></span></strong></p>
                                                    </td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                    </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; font-size: 12pt; line-height: 18.3999996185303px; font-family: 'Times New Roman', serif;">175 0075 19</span></strong></span></strong></span></strong></td>
                                                </tr>
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img width="209" height="81" border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/sacombank.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;">
                                                        <p style="margin: 0px; padding: 0px; line-height: 1.3em;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                    </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span><br style="margin: 0px; padding: 0px;">
                                                                </span></strong></p>
                                                    </td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                            </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><span style="margin: 0px; padding: 0px;" class="style3">0600.534.50981</span></span></strong></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px;">
                                            <div style="margin: 0px; padding: 0px;"><br style="margin: 0px; padding: 0px;">
                                                <table border="0" style="margin: 0px; padding: 0px; border-collapse: collapse; width: 890px; text-align: center;" class="thanh">
                                                    <tbody style="margin: 0px; padding: 0px;">
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/agribank.jpg"></td>
                                                            <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">&nbsp;6300.205.251.351</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/techcombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">1162.3675.672.015</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/sacombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">06000.7593.603</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/vietinbank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">71122.1908.891</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/achau.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">8912.1989</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/donga.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">0104.1107.72</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/seabak.png"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">1050.0000.187.752</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/vietcombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">0381.0027.873.48</span></strong></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <p class="MsoNoSpacing"><strong style="line-height: 1.7em; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; margin: 0px; padding: 0px;">-&nbsp;Sau khi chuyển khoản, vui lòng scan uỷ nhiệm chi/giấy chuyển tiền/biên lại ATM và email đến:</strong><span style="line-height: 1.7em; margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><strong style="margin: 0px; padding: 0px;"><a style="margin: 0px; padding: 0px; color: rgb(9, 81, 151);" href="mailto:weancpn@gmail.com">weancpn@gmail.com</a>&nbsp;</strong></span><strong style="line-height: 1.7em; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; margin: 0px; padding: 0px;">hoặc Gọi trực tiếp đến số:&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">(08) 3 720 555 2</span>&nbsp;để chúng tôi hỗ trợ.</strong></p>
                                        <p class="MsoNoSpacing"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;<b style="mso-bidi-font-weight:
normal">b. Thanh toán trực tiếp bằng tiền mặt hoặc thẻ (Thẻ Visa, Thẻ tín dụng...):</b></span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">- Quý khách đến văn phòng <strong>Công ty TNHH SX &amp; TM WEAN</strong> tại <strong><span style="font-weight:normal;mso-bidi-font-weight:bold">156 - Đường Đặng Văn Bi - Phường Bình Thọ - Quận Thủ Đức - TP.HCM</span></strong> để thực hiện thanh toán, nhân viên của chúng tôi sẽ hướng dẫn quý khách. Quý khách chú ý khi thanh <span style="mso-spacerun:yes">&nbsp;</span>toán phải có phiếu thu của Công ty TNHH SX &amp; TM WEAN <span style="mso-spacerun:yes">&nbsp;</span>và có mộc và chữ ký của Kế toán trưởng hoặc Giám đốc.</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">- Trong   trường hợp quý khách thanh toán bằng thẻ Visa hoặc Master bằng cách cà   thẻ tại Công ty của chúng tôi, Quý khách phải mang thẻ và phải đúng chủ   thẻ để lấy phiếu và ký nhận phiếu đã thanh toán. Chúng tôi sẽ không  chịu  trách nhiệm khi quý khách dùng thẻ của người khác để thanh toán.  Ngay  sau khi kiểm tra và nhận được báo "Có" từ Ngân hàng, chúng tôi sẽ  tiến  hành xuất hàng và giao hàng cho quý khách trong thời gian sớm  nhất.</span></p>
                                        <div>&nbsp;</div>
                                    </div>