<?php 
	$name           = $this->formText('name',$this->Item['name'],array('class'=>'txtmedium'));
        $alias          = $this->formText('alias',$this->Item['alias'],array('class'=>'txtmedium'));					
	$description	= $this->cmsReplaceString($this->Item['description']);
	$description	= $this->cmsEditor('description',$description,array('toolbar'=>'Default','language'=>'vi'));
        foreach ($this->itemSelectbox as $key => $val) {
            if ($val['level'] == 0) {
                $strCategory[$val['id']] = $val['name'];
            } else {
                $strCategory[$val['id']] .= str_repeat(' - ', $val['level']) . $val['name'];
            }
        }
        $parent 	= $this->formSelect('parent',$this->Item['parent'],array('style'=>'width:200px'),$strCategory);
        $brother_id 	= $this->formSelect('brother_id',$strCategory['id'],array('style'=>'width:200px'),$strCategory);
        $options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$valSta 	= $this->Item['status'];
	if($valSta == ''){$valSta = 0;}
	$status 	= $this->formRadio('status',$valSta,null,$options, '');
	$options 	= array($this->translate('No'),$this->translate('Yes'));
        
        //hình ảnh mô tả
        $inputInfo 	= array('name'=>'picture');
	$imgArr 	= !empty($this->Item['picture'])?array( FILES_URL . '/category/images194x177/'.$this->Item['picture']):'';
	$image 		= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/category/images194x177/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium_picture= $this->formHidden('current_stadium_picture',$this->Item['picture']);
        
        //hình ảnh mô tả
        $inputInfo 	= array('name'=>'picture1');
	$imgArr 	= !empty($this->Item['picture1'])?array( FILES_URL . '/category/images194x177/'.$this->Item['picture1']):'';
	$image 		= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture1'])){
	  	$urlimage   = FILES_URL . '/category/images194x177/'. $this->Item['picture1'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture1  = $imgimage ."<br/>" . $this->formFile('picture1',array('style'=>'margin-left:173px'));
	}else{
		$picture1  = $this->formFile('picture1',array('style'=>'margin-left:5px'));
	}
 	$current_stadium_picture1 = $this->formHidden('current_stadium_picture1',$this->Item['picture1']);
        
        //hình ảnh mô tả
        $inputInfo 	= array('name'=>'picture2');
	$imgArr 	= !empty($this->Item['picture2'])?array( FILES_URL . '/category/images194x177/'.$this->Item['picture2']):'';
	$image 		= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture2'])){
	  	$urlimage   = FILES_URL . '/category/images194x177/'. $this->Item['picture2'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture2  = $imgimage ."<br/>" . $this->formFile('picture2',array('style'=>'margin-left:173px'));
	}else{
		$picture2  = $this->formFile('picture2',array('style'=>'margin-left:5px'));
	}
 	$current_stadium_picture2= $this->formHidden('current_stadium_picture2',$this->Item['picture2']);
        
        //hình ảnh mô tả
        $inputInfo 	= array('name'=>'picture3');
	$imgArr 	= !empty($this->Item['picture3'])?array( FILES_URL . '/category/images194x177/'.$this->Item['picture3']):'';
	$image 		= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture3'])){
	  	$urlimage   = FILES_URL . '/category/images194x177/'. $this->Item['picture3'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture3  = $imgimage ."<br/>" . $this->formFile('picture3',array('style'=>'margin-left:173px'));
	}else{
		$picture3  = $this->formFile('picture3',array('style'=>'margin-left:5px'));
	}
 	$current_stadium_picture3= $this->formHidden('current_stadium_picture3',$this->Item['picture3']);
        
	$Input = array(
					array('Label'=>$this->translate('Tên Chuyên Mục'),'input'=>$name,'info'=>0),
					array('Label'=>$this->translate('Alias'),'input'=>$alias,'info'=>0),
                                        array('Label'=>$this->translate('Hình Ảnh'),'input'=>$picture),
                                        array('Label'=>$this->translate('Hình Ảnh'),'input'=>$picture1),
                                        array('Label'=>$this->translate('Hình Ảnh'),'input'=>$picture2),
                                        array('Label'=>$this->translate('Hình Ảnh'),'input'=>$picture3),
                                        array('Label'=>$this->translate('Chuyên Mục Cha'),'input'=>$parent,'info'=>0),
                                        array('Label'=>$this->translate('Chèn vào trước'),'input'=>$brother_id,'info'=>0),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
					array('Label'=>$this->translate('Mô Tả'),'input'=>$description,'style'=>'margin-left:174px'),
					);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
                             <?php
				echo $current_stadium_picture;
                                echo $current_stadium_picture1;
                                echo $current_stadium_picture2;
                                echo $current_stadium_picture3;
                                echo $this->partialLoop('rows.php',$Input);
                             ?>                              
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>