<?php 
	$name 		= $this->formText('name',$this->Item['name'],array('class'=>'txtmedium'));
	$note    	= $this->formTextarea('note',str_replace("\\","",$this->Item['note']),array('rows'=>'10'));
	$order 		= $this->formText('order',$this->Item['order'],array('class'=>'txtshort'));	
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$status 	= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
 	
	$options1 	= array(
						$this->translate('Select a units'),
						$this->translate('Meters'),
						$this->translate('Centimeters'),
						$this->translate('Millimeters'),
						);
	$units 	= $this->formSelect('units',$this->Item['units'],null,$options1, ' ');
	
	$Input 		= array(
						array('Label'=>$this->translate('Name size'),'input'=>$name,'info'=>0),
						array('Label'=>$this->translate('Units'),'input'=>$units,'info'=>0),
						array('Label'=>$this->translate('Note'),'input'=>$note,'info'=>0),
						array('Label'=>$this->translate('Order'),'input'=>$order,'info'=>0),
						array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
						);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input) .$current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>