<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$langTmp = $ssFilter['lang'];
	$lang = '';
	if(!empty($langTmp)){
		$lang = '/lang/' . $langTmp;
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblName 		= $this->cmsLinkSort($this->translate('Name size'),'s.name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	$lblOrder 		= $this->cmsLinkSort($this->translate('Order'),'s.order',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblId 		= $this->cmsLinkSort('ID','id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now',$this->translate('Search'),
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords',$this->translate('Clear'),
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;
?>
<form name="appForm" method="post" action="">
                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php echo $strSearch;?>
									</div>
								</div>	
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lblName ?></th>
                                            <th width="150"><?php echo $this->translate('Units')?></th>
                                            <th width="200"><?php echo $this->translate('Status')?></th>
                                            <th width="150"><?php echo $lblOrder;?></th>
                                            <th width="150">Control</th>
                                            <th width="100"><?php echo $lblId?></th>
                                        </tr>
                                    </thead>
									<?php
										foreach($this->Items as $key => $val){
											$name 		= $val['name'];
											
											
											$id 		= $val['id'];
											$status 	= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												$status = $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive', $linkStatus, $id);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status = $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active', $linkStatus, $id);
											}
											
											$options1 	= array(
												$this->translate('Select a units'),
												$this->translate('Meters'),
												$this->translate('Centimeters'),
												$this->translate('Millimeters'),
											);
											$units	= $this->formSelect('units['.$id.']',$val['units'],null,$options1,null);
											
											$order				= $this->formText('order['.$id.']',$val['order'],array('class'=>'order'));
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $lang);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $lang);
											$btnDelete =  $this->cmsAjaxButton('ajax-delete-item', 'Delete Item', 'Delete', $linkDelete, $id);
										
											$strIconButton	= $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
											$cls = 'row0';
											if($key%2 == 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="<?php echo $cls?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><a href="<?php echo $linkEdit?>"><?php echo $name;?></a></td>
                                        <td align="left"><?php echo $units?></td>
                                        <td align="center"><?php echo $status;?></td>                               
                                        <td align="center"><?php echo $order;?></td>                                  
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->
								
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>