<?php 
	$name 			= $this->formText('name',str_replace("\\","",$this->Item['name']),array('class'=>'txtmedium'));
	$alias 			= $this->formText('alias',str_replace("\\","",$this->Item['alias']),array('class'=>'txtmedium'));
	$alt_seo 		= $this->formText('alt_seo',str_replace("\\","",$this->Item['alt_seo']),array('class'=>'txtmedium'));
	$title_seo 		= $this->formText('title_seo',str_replace("\\","",$this->Item['title_seo']),array('class'=>'txtmedium'));
	$picture 		= $this->formFile('picture',array('style'=>'width: 250px'));
	$price 			= $this->formText('price',$this->Item['price'],array('class'=>'txtmedium','style'=>'width: 194px'));
	$selloff 		= $this->formText('selloff',$this->Item['selloff'],array('class'=>'txtmedium','style'=>'width: 194px'));
	$summary        = $this->formTextarea('summary',str_replace("\\","",$this->Item['summary']),array('rows'=>'10'));
	$description_html 	= $this->formTextarea('description_html',str_replace("\\","",$this->Item['description_html']),array('rows'=>'10'));									
	$keywords_html 		= $this->formTextarea('keywords_html',str_replace("\\","",$this->Item['keywords_html']),array('rows'=>'10'));	
	$GroupCategory = $this->cmsSelect('menu_id',$this->Item['menu_id'],$this->tblGroupCategory,
										array('style'=>'width:200px','size'=>10));
	$content		= $this->cmsReplaceString($this->Item['content']);
	$content		= $this->cmsEditor('content',str_replace("\\","",$content),array('toolbar'=>'Default','language'=>'vi'));
	
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$status 	= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	
	$options 	= array($this->translate('No'),$this->translate('Yes'));
	$special 	= $this->formRadio('special',$this->Item['special'],null,$options, ' ');
	
	$options 	= array($this->translate('No'),$this->translate('Yes'));
	$featured 	= $this->formRadio('featured',$this->Item['featured'],null,$options, ' ');
	
	/*...........Picture............*/
	$imgArr 		= !empty($this->Item['picture'])?array( FILES_URL . '/products/images100x100/'.$this->Item['picture']):'';
	$image 	= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/products/images100x100/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));	
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium = $this->formHidden('current_stadium_picture',$this->Item['picture']);  
	
	$Input = array(
					array('Label'=>$this->translate('Product name'),'input'=>$name,'info'=>0),
					array('Label'=>$this->translate('Alias'),'input'=>$alias,'info'=>0),
					array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>0),
					array('Label'=>$this->translate('Alt SEO'),'input'=>$alt_seo,'info'=>0),
					array('Label'=>$this->translate('Title SEO'),'input'=>$title_seo,'info'=>0),
					array('Label'=>$this->translate('Price'),'input'=>$price,'info'=>0),
					array('Label'=>$this->translate('Sale Off'),'input'=>$selloff,'info'=>0),
					array('Label'=>$this->translate('Category'),'input'=>$GroupCategory,'info'=>0),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
					array('Label'=>$this->translate('Special'),'input'=>$special,'info'=>0),
					array('Label'=>$this->translate('Featured'),'input'=>$featured,'info'=>0),
                    array('Label'=>$this->translate('Summary'),'input'=>$summary,'info'=>0),
                    array('Label'=>$this->translate('Description HTML'),'input'=>$description_html,'info'=>0),
					array('Label'=>$this->translate('Keywords HTML'),'input'=>$keywords_html,'info'=>0),
					array('Label'=>$this->translate('Content'),'input'=>$content,'style'=>'margin-left:174px'),
					);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader"><?php echo $this->translate('Information')?></div>								
								<?php echo $this->partialLoop('rows.php',$Input) . $current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>