<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&appId=290092294466858&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php

	$url = 'http://' . $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
	$lang = $this->arrParam['lang'];
    if(empty($lang)){
        $lang = 'vi';
    }else{
        $lang = $this->arrParam['lang'];
    }
    
    $page = 1;

	$item 	= $this->Item;
	$menu	= $this->menu;
	$name		= str_replace("\\","",$item['name']);
	
	//$units = $item['units'];
	//if(!empty($units)) $units = '<tr><td class="name-title"><b>Đơn vị phát hành</b></td> <td>'.$units.'</td></tr>';
	
	$warranty = $item['warranty'];
	if(!empty($warranty)) $warranty = '<tr><td class="name-title"><b>Bảo hành</b></td> <td>'.$warranty.'</td></tr>';
	
	
	$filter = new Zend_Filter();
	$multiFilter = $filter	->addFilter(new Zend_Filter_StringToLower(array('encoding'=>'UTF-8')))
									->addFilter(new Zend_Filter_StringTrim())
						 			->addFilter(new Zend_Filter_Alnum(true))
//						  			->addFilter(new Zend_Filter_PregReplace(array('match'=>'#\s+#','replace'=>'-')))
						  			->addFilter(new Zend_Filter_Word_SeparatorToDash())
						  			->addFilter(new Zendvn_Filter_RemoveCircumflex());
	$publisher = $item['publisher'];
	$alias_pub = $filter->filter($publisher);
	$urlOptions = array('module'=>'products','controller'=>'index',
													'action'=>'index',
													'publisher'=>$alias_pub,
													'page'=>$page,
													'lang'=>$lang);
	$linkPublisher = $this->url($urlOptions,'products-pub');
	if(!empty($publisher)) $publisher = '<tr><td class="name-title"><b>Nhà sản xuất</b></td> <td><a href="'.$linkPublisher.'">'.$publisher.'</a></td></tr>';
	
	
	$code = $item['code'];
	if(!empty($code)) $code = '<tr><td class="name-title"><b>Mã sản phẩm</b></td> <td>'.$code.'</td></tr>';
	
	$hits = '<tr><td class="name-title"><b>Số lần xem</b></td> <td> '.$item['hits'].'</td></tr>';
	
	$price = $item['price'];
	if(!empty($price)) $price = '<tr><td class="name-title"><b>Giá</b></td> <td class="col-green"> '.number_format($price,0) . ' VND</td></tr>';
	
	$content 	= $item['content'];
	$content 	= str_replace("\\"," ",$content);
	
	$info 		= $item['info'];
	$info	 	= str_replace("\\"," ",$info);
	
	$sale		= $menu['sale'];
	
	$menu_id	= $item['menu_id'];
	include 'includes/sale.php';
	
	$price 		= '';
	if(!empty($item['price'])) $price = '<tr><td class="name-title"><b>Giá</b></td> <td class="col-green"> '.number_format($item['price'],0) . ' VND</td></tr>';
	
	
	
	if (empty($item['selloff'])){
		$sale_off 	= '<tr><td class="name-title"><b>Giá bán</b></td> <td class="col-red">' . number_format($item['price'],0) . ' VND</td></tr>';
	}
	$val_sell 	= '';
	if(!empty($item['val_sell']) || $item['val_sell'] != 0){
		$sale_off 	= $item['selloff'];
		$sale_off 	= '<tr><td class="name-title"><b>Giá bán</b></td> <td class="col-red">' . number_format($sale_off,0) . ' VND</td></tr>';
		$val_sell 	= $item['val_sell'];
		$val_sell 	= '<td class="name-title"><b>Giảm giá</b></td> <td class="col-ju">'. $val_sell .'%</td>';
	}
	if(!empty($sale) && (empty($item['val_sell']) || $item['val_sell'] == 0)){
		$sale_off    = $item['price'] - ($item['price'] * $sale/100) ;
		$sale_off 	= '<tr><td class="name-title"><b>Giá bán</b></td> <td class="col-red">' . number_format($sale_off,0) . ' VND</td></tr>';
		$val_sell 	= $sale;
		$val_sell 	= '<td class="name-title"><b>Giảm giá</b></td> <td class="col-ju">'. $val_sell .'%</td>';
	}
	if($item['price'] == 0){
		$price = '<tr><td class="name-title"><b>Giá bán</b></td> <td class="col-red">Liên hệ</td></tr>';
		$sale_off ='';
	}
    
	
	
	$alt = $item['name'];
	if(!empty($item['alt_seo'])) $alt = $item['alt_seo'];
	$alt 		= str_replace("\\"," ",$alt);
    
    if(!empty($item['picture'])){
	    $linkImg	= FILES_URL . '/products/images450x450/' . $item['picture'];
	    $linkImg2	= FILES_URL . '/products/orignal/' . $item['picture'];
	    $picture 	= '<img src="'. $linkImg .'" alt="'.$alt.'" />';
	    $image 		= '<img style="max-width:600px" src="'. $linkImg2 .'" alt="'.$alt.'" />';
    }else{
	    $linkImg	= $this->imgUrl . '/no-image.jpg';
	    $picture 	= '<img src="'. $linkImg .'" alt="'.$alt.'" />';
	    $image 		= '<img src="'. $linkImg .'" alt="'.$alt.'" />';
    }
    
    $linkCart = $this->baseUrl('/products/index/add-item/id/' . $item['id']);
    
    $urlHome 		= array('module'=>'default','controller'=>'index','action'=>'index');
   	$linkHome 		= $this->url($urlHome,'home');
   	
    $urlContact 	= array('module'=>'default','controller'=>'index','action'=>'contact');
   	$linkContact 	= $this->url($urlContact,'contact');
   	
   	$cat 		= $this->Cat;
    $category	= $cat['name'];
    $urlOptions = array('module'=>'news','controller'=>'index',
						'action'=>'category',
                    	'cid'=> $cat['id'],
						'name'=>$cat['alias'],
                    	'lang'=>$lang,
                    	'page'=>$page);
   	$linkDetail = $this->url($urlOptions,'products-category');
?>

<script type="text/javascript">
	function fancyBox(elem){
		elem = $(elem);
		if (!elem.data("fancybox")) {
			elem.data("fancybox", true);
			elem.fancybox({
				'titleShow' 	: false,
				'transitionIn'	: 'elastic',
				'transitionOut'	: 'elastic',
				'centerOnScroll': true
			}).trigger('click');
		}
		return false; 
	}
</script>

<div class='right width-78'>
	<div class="box-right-pro width-100 detail">
		<div class='cnt-right width-100'>
						<?php
							 $pubTitle 	= '<h2><a title="'.$category.'" class="color-blue" href="'.$linkDetail.'"> '.$category.'<span> &#187; </span></a></h2> '; 
						?>
						<div class="sub-box-right"><span class='icon-right'><img src="<?php echo $this->imgUrl ?>/icon/icon-sub-right.png"></span><a class="color-blue" href="<?php echo $linkHome?>">Home &#187; </a><?php echo $pubTitle ?> <h1><?php echo $name?></h1></div>
						<?php
		                	$itemAdvert	= $this->cmsAdvert('adv-detail width-100','home',FALSE,true,'pro-detail', null);
		                    foreach ($itemAdvert as $adv) {
		                         echo $adv;
		                    } 
		                ?>
                        <div class="box-cnt box-detail">
                            <div class="bor-img width-40">
                                <a onclick="return fancyBox(this);" id="various1" href="#inline1" title="<?php echo $name?>"><?php echo $picture?></a>
                                <div style="display: none;">
									<div class='inline' id="inline1">
										<?php echo $image?>
										<div class="overlay"></div>
									</div>
								</div>
                                <a class='cart' href='<?php echo $linkContact?>'>Đặt hàng theo yêu cầu</a>
                                <button class='btn-ins'>Mua trả góp</button>
                                <button id="opener">PHƯƠNG THỨC THANH TOÁN</button>
                                <div id="dialog" title="Phương Thức Thanh Toán">
                                    <div>
                                        <p class="MsoNoSpacing" style="text-align:justify"><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Hướng dẫn thanh toán </span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1. PHƯƠNG THỨC GIAO HÀNG - TRẢ TIỀN MẶT:</span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Phương thức Giao hàng - Trả tiền mặt chỉ áp dụng đối với những khu vực chúng tôi hỗ trợ giao nhận miễn phí (tham khảo thêm <u>chính sách giao nhận</u>) hoặc trả tiền mua hàng trực tiếp tại Công ty TNHH SX &amp; TM WEAN</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;2. PHƯƠNG THỨC THANH TOÁN TRƯỚC: </span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Chuyển tiền, chuyển khoản, thanh toán trực tiếp bằng tiền mặt <span style="mso-spacerun:yes">&nbsp;</span>hoặc qua thẻ tại văn phòng của chúng tôi</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><b style="mso-bidi-font-weight:
normal"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">a. Chuyển tiền/chuyển khoản:</span></b></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Áp dụng cho khách <span style="mso-spacerun:yes">&nbsp;</span>hàng <span style="mso-spacerun:yes">&nbsp;</span>ngoài khu vực hỗ trợ giao nhận miễn phí và khách hàng có nhu cầu sử dụng phương thức thanh <span style="mso-spacerun:yes">&nbsp;</span>toán <span style="mso-spacerun:yes">&nbsp;</span>này</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify">&nbsp;</p>
                                        <table border="0" style="margin: 0px; padding: 0px; border-collapse: collapse; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; width: 695px; float: left;" class="thanh">
                                            <tbody style="margin: 0px; padding: 0px;">
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img style="margin: 0px; padding: 0px; border: 0px none;" alt="vietcom" src="http://congtynem.com/vi/public/files/editor-upload/vietcom.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span></span></strong></td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                            </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; font-size: 12pt; line-height: 18.3999996185303px; font-family: 'Times New Roman', serif;">0381 000 415 899</span></strong></span></strong></td>
                                                </tr>
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img style="margin: 0px; padding: 0px; border: 0px none;" alt="acb" src="http://congtynem.com/vi/public/files/editor-upload/acb.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;">
                                                        <p style="margin: 0px; padding: 0px; line-height: 1.3em;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                                </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span></span></strong></span></span></strong></p>
                                                    </td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                    </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; font-size: 12pt; line-height: 18.3999996185303px; font-family: 'Times New Roman', serif;">175 0075 19</span></strong></span></strong></span></strong></td>
                                                </tr>
                                                <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img width="209" height="81" border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/sacombank.jpg"></td>
                                                    <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;">
                                                        <p style="margin: 0px; padding: 0px; line-height: 1.3em;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">--- Chủ tài khoản ---&nbsp;<br style="margin: 0px; padding: 0px;">
                                                                    </span><span style="margin: 0px; padding: 0px; font-size: 11pt; font-family: 'times new roman', times;">CÔNG TY TNHH SX &amp; TM WEAN</span><br style="margin: 0px; padding: 0px;">
                                                                </span></strong></p>
                                                    </td>
                                                    <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221); text-align: center;"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">Số Tài Khoản&nbsp;<br style="margin: 0px; padding: 0px;">
                                                            </span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><span style="margin: 0px; padding: 0px;" class="style3">0600.534.50981</span></span></strong></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px;">
                                            <div style="margin: 0px; padding: 0px;"><br style="margin: 0px; padding: 0px;">
                                                <table border="0" style="margin: 0px; padding: 0px; border-collapse: collapse; width: 695px;" class="thanh">
                                                    <tbody style="margin: 0px; padding: 0px;">
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/agribank.jpg"></td>
                                                            <td width="33%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td width="34%" style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">&nbsp;6300.205.251.351</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/techcombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">1162.3675.672.015</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/sacombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">06000.7593.603</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/vietinbank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">71122.1908.891</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/achau.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">8912.1989</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/donga.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">0104.1107.72</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/seabak.png"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);" class="style3">1050.0000.187.752</span></strong></td>
                                                        </tr>
                                                        <tr style="margin: 0px; padding: 0px; border: 1px solid rgb(221, 221, 221);">
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><img border="0" style="margin: 0px; padding: 0px; border: 0px none;" alt="alt" src="http://congtynem.com/vi/public/files/editor-upload/vietcombank.jpg"></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Chủ tài khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Phạm Minh Tuấn</span></strong></td>
                                                            <td style="margin: 0px; padding: 0px; border-style: solid; border-color: rgb(221, 221, 221);"><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px;">Số Tài Khoản :</span>&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">0381.0027.873.48</span></strong></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <p class="MsoNoSpacing"><strong style="line-height: 1.7em; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; margin: 0px; padding: 0px;">-&nbsp;Sau khi chuyển khoản, vui lòng scan uỷ nhiệm chi/giấy chuyển tiền/biên lại ATM và email đến:</strong><span style="line-height: 1.7em; margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><strong style="margin: 0px; padding: 0px;"><a style="margin: 0px; padding: 0px; color: rgb(9, 81, 151);" href="mailto:weancpn@gmail.com">weancpn@gmail.com</a>&nbsp;</strong></span><strong style="line-height: 1.7em; color: rgb(51, 51, 51); font-family: arial, helvetica, sans-serif; font-size: 13px; margin: 0px; padding: 0px;">hoặc Gọi trực tiếp đến số:&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">(08) 3 720 555 2</span>&nbsp;để chúng tôi hỗ trợ.</strong></p>
                                        <p class="MsoNoSpacing"><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;<b style="mso-bidi-font-weight:
normal">b. Thanh toán trực tiếp bằng tiền mặt hoặc thẻ (Thẻ Visa, Thẻ tín dụng...):</b></span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">- Quý khách đến văn phòng <strong>Công ty TNHH SX &amp; TM WEAN</strong> tại <strong><span style="font-weight:normal;mso-bidi-font-weight:bold">156 - Đường Đặng Văn Bi - Phường Bình Thọ - Quận Thủ Đức - TP.HCM</span></strong> để thực hiện thanh toán, nhân viên của chúng tôi sẽ hướng dẫn quý khách. Quý khách chú ý khi thanh <span style="mso-spacerun:yes">&nbsp;</span>toán phải có phiếu thu của Công ty TNHH SX &amp; TM WEAN <span style="mso-spacerun:yes">&nbsp;</span>và có mộc và chữ ký của Kế toán trưởng hoặc Giám đốc.</span></p>
                                        <p class="MsoNoSpacing" style="text-align:justify"><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp;</span><span style="font-size:12.0pt;
font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">- Trong   trường hợp quý khách thanh toán bằng thẻ Visa hoặc Master bằng cách cà   thẻ tại Công ty của chúng tôi, Quý khách phải mang thẻ và phải đúng chủ   thẻ để lấy phiếu và ký nhận phiếu đã thanh toán. Chúng tôi sẽ không  chịu  trách nhiệm khi quý khách dùng thẻ của người khác để thanh toán.  Ngay  sau khi kiểm tra và nhận được báo "Có" từ Ngân hàng, chúng tôi sẽ  tiến  hành xuất hàng và giao hàng cho quý khách trong thời gian sớm  nhất.</span></p>
                                        <div>&nbsp;</div>
                                    </div>
                                  </div>
                                <?php 
                                	include 'includes/installment.php';
                                ?>
                            </div>
                            <div class="desc">
                                <h1 class="color-blue"><?php echo $name ?></h1>
                                <table class='detail-info' cellpadding="0" cellspacing="0">
	                                <?php echo $code?>
	                                <?php echo $publisher?>
	                                <?php echo $hits?>
	                                <?php echo $price?>
	                                <?php echo $sale_off?>
	                                <?php echo $val_sell?>
	                                <?php echo $warranty?>
                                </table>
                                <?php
                                	$itemPrice 	= $this->Price_pro ;
                                	if (!empty($itemPrice)){
                                ?>
                                <div class='tab_main'>
	                                <table class='tab_price'>
	                                	<thead>
	                                		<tr>
	                                			<th width="23%">Quy cách</th>
	                                			<th width="20%">Giá gốc (Vnd)</th>
	                                			<th width="20%">Giá bán (Vnd)</th>
	                                			<th width="18%">Giảm (%)</th>
	                                			<th>Mua hàng</th>
	                                		</tr>
	                                	</thead>
	                                	<tbody>
	                                		<?php
	                                				foreach ($itemPrice as $keyPri => $valPri) {
	                                					$size = $valPri['size'];
														if($valPri['unit_name'] == 1) $unit_name = 'Meters';
														if($valPri['unit_name'] == 2) $unit_name = 'Centimeters';
														if($valPri['unit_name'] == 3) $unit_name = 'Millimeters';
														$pri_pro = $valPri['price'];
														$val_sell_pro  = $valPri['val_sell'];
														$sale_pro = $valPri['selloff'];
														if(empty($sale_pro)) $sale_pro = $pri_pro;
														
														if(!empty($valPri['val_sell']) || $valPri['val_sell'] != 0){
															$val_sell_pro = $valPri['val_sell'];
															$sale_pro = $valPri['selloff'];
														}
		                                				if((!empty($item['val_sell']) || $item['val_sell'] != 0) && (empty($valPri['val_sell']) || $valPri['val_sell'] == 0)){
		                                					$val_sell_pro = $item['val_sell'] ;
		                                					$sale_pro = $valPri['price'] - ($valPri['price'] * $item['val_sell']/100);
														}
														if((empty($item['val_sell']) || $item['val_sell'] == 0) && (empty($valPri['val_sell']) || $valPri['val_sell'] == 0)){
														if(!empty($sale)){
																$val_sell_pro = $sale ;
																$sale_pro = $valPri['price'] - ($valPri['price'] * $sale/100);
															}
														}
														$linkCartPro = $this->baseUrl('/products/index/add-item/id/' . $item['id'] . '/priID/' . $valPri['id']);
	                                			?>
	                                		<tr>
	                                			<td class='size_pro'><?php echo $size?></td>
	                                			<td><?php echo number_format($pri_pro,0)?></td>
	                                			<td class='sale_pro'><?php echo number_format($sale_pro,0) ?></td>
	                                			<td><?php echo $val_sell_pro?></td>
	                                			<td><a class='cart_pro' href='<?php echo $linkCartPro?>'>Mua hàng</a></td>
	                                		</tr>
	                                		<?php
	                                				} 
	                                		?>
	                                	</tbody>
	                                </table>
	                             </div>
                                <?php
                                	 } 
                                ?>
                            </div>
                            <div class="clear"></div>
                            <div class="line"></div>
                        </div>
                        <div class="clear"></div>
                        <h3 class='sub-detail cnt-01 sub-active'>Giới thiệu về sản phẩm</h3>
                        <div class="cnt-detail">
                        	<div class="content-01">
	                        	<?php 
	                        		echo $content ;
	                        		$url = Zend_Controller_Front::getInstance()->getRequest()->getPathInfo();
	                        		$link_pro = $this->baseUrl($url); 
	                        	?>
	                        	<div>
		                        	<div class='qr-code'>
		                        		<script type="text/javascript">
											var uri=window.location.href;
											document.write("<img src='http://api.qrserver.com/v1/create-qr-code/?data="+encodeURI(uri)+"&size=150x150'/>");
										</script>
									</div>
									<p style='font-size: 11pt; text-align: center;'>Mã QR-CODE</p>
								</div>
                        	</div>
                        	<div class="content-02">
                        	<?php 
                        		echo $info ;
                        	?>
                        	</div>
                        	<div class='cnt-info-contact'>
                        		<div class='sub-info-contact'>Thông tin liên hệ</div>
                        		<h2>HỆ THỐNG PHÂN PHỐI NỆM TRỰC TUYẾN TẠI CONGTYNEM.COM</h2>
                        		<?php
									$tblContact	= new Zendvn_Models_Contact();
									$contact	= $tblContact->listItem($this->arrParam,array('task'=>'public'));
									if (!empty($contact)){
										foreach ($contact as $key => $value){
											$title		= str_replace("\\","",$value['title']);
											$address  	= str_replace("\\","",$value['address']);
								?>
                        		<p><b><?php echo $title?></b></p>
								<p>ĐC : <?php echo $address?></p>
								<?php
										}
									}
								?>
								<?php
									$tblContact	= new Zendvn_Models_Contact();
									$contact	= $tblContact->listItem($this->arrParam,array('task'=>'row'));
									$hotline	= str_replace("\\","",$contact['hotline']);
									$phone  	= str_replace("\\","",$contact['phone']);
									$code  		= str_replace("\\","",$contact['code']);
									$mail  		= str_replace("\\","",$contact['email']);
									$fax  		= str_replace("\\","",$contact['fax']);
									$website  	= str_replace("\\","",$contact['website']);
									$contentC  	= str_replace("\\","",$contact['content']);
								?>
								<p>Hotline : <?php echo $hotline?>  -  Tel : <?php echo $phone?></p>
								<p>Mã số thuế : <?php echo $code?>  - Mail : <?php echo $mail?></p>
								<p>Fax : <?php echo $fax?>  -  Website : <?php echo $website?></p>
								<p><?php echo $contentC?></p>
                        	</div>
                        	<div class='tag'>
                        		<span><b>TAG: </b></span> 
                        		<h2><a href='<?php echo $link_pro?>'><?php echo $name?>, </a></h2>
                        		<?php
                        			$tblMenu 	= new Zendvn_Models_Menus();
    								$menu		= $tblMenu->listItem($this->arrParam,array('task'=>'products-child'));
    								$id 			= $menu['id'];
    								$childMenu		= $tblMenu->listItem($this->arrParam,array('task'=>'find-products','cid'=>$id));
    								foreach ($childMenu as $keyss => $value){
							            	$name	= str_replace("\\"," ",$value['name']);
							                $urlOptions = array('module'=>'products','controller'=>'index',
																'action'=>'category',
											                    'cid'=> $value['id'],
																'name'=>$value['alias'],
											                    'lang'=>$lang,
											                    'page'=>$page);
											$linkDetail = $this->url($urlOptions,'products-category');
											if ($keyss != 0){
                        		?>
                        		<h2><a href='<?php echo $linkDetail?>'><?php echo $name?>, </a></h2>
                        		<?php 
											}else{
								?>
								<h2><a href='<?php echo $linkDetail?>'><?php echo $name?></a></h2>
								<?php 
											}
    								}
                        		?>
                        	</div>
                        </div>
                        <div class="fb-like" data-href="<?php echo $url?>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                        <div class='google'><div class="g-plusone" data-annotation="inline" data-width="300"></div></div>
                        
                        
                        	<?php
                        		$info = new Zendvn_System_Info();
								$memberInfo = $info->getMemberInfo('id');
								if($memberInfo != ''){
									$tbltUser 	= new Zendvn_Models_Users();
									$user 		= $tbltUser->listItem($this->arrParam,array('user_id'=>$memberInfo,'task'=>'public'));
									$group_id 	= $user['group_id'];
									$tblUsername	= $user['first_name'] . ' ' . $user['last_name'];
									$tblEmail		= $user['email'];
								}else{
									$tblUsername	= str_replace("\\","",$this->arrParam['user_name']);
									$tblEmail		= str_replace("\\","",$this->arrParam['email']);
								}
                        		$user_name 	= $this->formText('user_name',$tblUsername,array('class'=>'txtmedium'));
								$email 		= $this->formText('email',$tblEmail,array('class'=>'txtmedium'));
								$title_com 	= $this->formText('title_com',str_replace("\\","",$this->arrParam['title_com']),array('class'=>'txtmedium'));
								$content    = $this->formTextarea('content',str_replace("\\","",$this->arrParam['content']),array('rows'=>'5'));
								$captcha 	= 	$this->captcha;
								$txtCaptcha = 	$this->formText('captcha','');
								$txtID 		= 	$this->formHidden('captchaID',$this->captcha_id);		
								$urlCaptch	= $this->baseUrl('default/index/captcha-image');	
								$inputCaptcha	= $this->formText('captcha',null,array("class"=>"code")); 
								$submit    = $this->formSubmit('submit','Gửi bình luận',null);
								$com_show	= '';
								if (count ( $this->errors ) > 0) {
									$errors = $this->formErrors ( $this->errors, array ('id' => 'errors' ) );
									$com_show = 'com-show';
								}
                        	?>
                        	<div class='not-succ'>
		                       <?php
		                       		if(!empty($this->noteSucc)) echo $this->noteSucc;
		                       ?>
                       		</div>
                       <div class='submit-com'>Bình luận</div>
                       <div class='comment width-100 <?php echo $com_show?>'>
                       		<div class='close'><img src="<?php echo $this->imgUrl ?>/icon/icon-close-20.png" /></div>
                        	<div class='line'></div>
                        	<div class='box-comment'>
                        		<?php if(empty($this->messages[0])):?>
                        		<form action="#" method="post"  enctype="multipart/form-data">
                        			<div class='lev-com'>
                        				<span class='sub-com'>Tên:</span>
                        				<?php echo $user_name?>
                        				<div><?php if(!empty($this->errors['user_name'])):echo '<p class="msg_error">'.$this->errors['user_name'].'</p>';endif;?></div>
                        				<input type="hidden" name="url" value="<?php echo $url?>">
                        			</div>
                        			<div class='lev-com'>
                        				<span class='sub-com'>Email:</span>
                        				<?php echo $email?>
                        				<div><?php if(!empty($this->errors['email'])):echo '<p class="msg_error">'.$this->errors['email'].'</p>';endif;?></div>
                        			</div>
                        			<div class='lev-com'>
                        				<span class='sub-com'>Tiêu đề:</span>
                        				<?php echo $title_com?>
                        				<div><?php if(!empty($this->errors['title_com'])):echo '<p class="msg_error">'.$this->errors['title_com'].'</p>';endif;?></div>
                        			</div>
                        			<div class='lev-com'>
                        				<span class='sub-com'>Nội dung:</span>
                        				<?php echo $content?>
                        				<div><?php if(!empty($this->errors['content'])):echo '<p class="msg_error">'.$this->errors['content'].'</p>';endif;?></div>
                        			</div>
                        			<div class="lev-com">
					                	<span class='sub-com'>Xác nhận: </span>
					                 	<?php echo $inputCaptcha;?>                            	
					                 	<?php if(!empty($this->errors['captcha'])):echo '<p class="msg_error">'.$this->errors['captcha'].'</p>';endif;?>
						            </div>
						            <div class="lev-com">
										<div class="border-img"><?php echo $txtID . $captcha;?></div>
						            </div>
                        			<div class='lev-com'>
                        				<?php echo $submit?>
                        			</div>
                        		</form>
                        		<?php else:
						           echo '<div class="notice">'.$this->messages[0].'</div>';
						      endif;?>
                        	</div>
                        </div>
                        <?php
                        	$tblComment	= new Zendvn_Models_CommentsProducts();
                        	$itemsCom	=  $tblComment ->listItem($this->arrParam,array('task'=>'list'));
                        	if(!empty($itemsCom)){
                        ?>
                        <div class='cnt-comment'>
                        	<?php
                        		foreach ($itemsCom as $keyCom => $valCom) {
                        			$row	 = 'row-1';
                        			if (($keyCom+1)%2 == 0)$row	 = 'row-2';
                        			$title		= str_replace("\\","",$valCom['title']);
                        			$user		= str_replace("\\","",$valCom['user_name']);
                        			$created	= $valCom['created'];
                        			$content	= $valCom['content'];
                        			$content	= strip_tags($content,'<a><b><i><u><img><br><p>');  
                        	?>
                        	<div class='box-cnt-comment <?php echo $row?>'>
                        		<h2><?php echo $title?></h2>
                        		<div class='info-com'>
                        			<span class='user-name'><?php echo $user?></span>
                        			<span class='creat-day'><?php echo $created?></span>
                        		</div>
                        		<div class='content-com'>
                        			<?php echo $content?>
                        		</div>
                        	</div>
                        	<?php
                        		} 
                        	?>
                        </div>
                        <?php
                        	} 
                        ?>
                        <!--------------------BOX CONTENT (End) ----------------------> 
                    	</div>
					<div class='width-100'>
						<div class='sub-box-right'><span class='icon-right'><img src="<?php echo $this->imgUrl ?>/icon/icon-sub-right.png"></span><p>Sản phẩm cùng chuyên mục</p></div>
                		<div class="group width-100 mar-top-20">
							<?php
								$tblItems 	= new Zendvn_Models_ProItem();
	                            $items 		= $tblItems -> listItem($this->arrParam,array('task'=>'fav-detail'));
	                        	if(!empty($items)){
	                        ?>
	                        <div class="cnt-right mar-top-5 width-100">
	                        <?php
	                        	foreach ($items as $key => $value){
	                        			$cutTring 	= new Zendvn_File_CutTring();
	                    				$name		= str_replace("\\","",$value['name']);
	                    				$name		= $cutTring->cutTring(25, $name, null);
	                    				
	                    				$alt		= str_replace("\\","",$value['alt_seo']);
	                    				if(!empty($value['alt_seo'])) $alt = str_replace("\\","",$value['name']);
	                    				
					            		$summary	= str_replace("\\","",$value['summary']);
					            		$summary	= $cutTring->cutTring(120, $summary, null);
					            		$price 		= '<p class="price float-left">' . number_format($value['price'],0) . ' VND</p>';
					            		
					            		$sale		= $value['sale'];
					            		$val_sell 	= '';
					            		$sale_off 	= '';
			                        	if ($value['selloff'] != 0){
												$sale_off	= '<p class="sale">' . number_format($value['selloff'],0) . ' VND</p>';
												$val_sell 	= '<div class="icon-sale">'. $value['val_sell'] .'%</div>';
											}
											$price 		= '<p class="price-right-pro">' . number_format($value['price'],0) . ' VND</p>';
											if($value['val_sell'] != 0){
												$price 	= '<p class="price-right-pro  line-through">' . number_format($value['price'],0) . ' VND</p>';
											}
											if ($sale != 0){
												$sale_off 	= $value['price'] - ($value['price']*$sale/100);
												$sale_off	= '<p class="sale">' . number_format($sale_off,0) . ' VND</p>';
												$price 		= '<p class="price-right-pro line-through">' . number_format($value['price'],0) . ' VND</p>';
												$val_sell 	= '<div class="icon-sale">'. $sale .'%</div>';
												if($value['val_sell'] != 0){
													$val_sell 	= '<div class="icon-sale">'. $value['val_sell'] .'%</div>';
													$sale_off	= '<p class="sale">' . number_format($value['selloff'],0) . ' VND</p>';
												}
											}
					            		if($value['price'] == 0) $price = '<p style="color:red; font-size:1em" class="price">Liên hệ</p>';
					            		
					            		
					            		if(!empty($value['picture'])){
										    $linkImg	= FILES_URL . '/products/images450x450/' . $value['picture'];
										    $picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
									    }else{
										    $linkImg	= $this->imgUrl . '/no-image.jpg';
										    $picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
									    }
	                    				$lang = $this->arrParam['lang'];
					                    if(empty($lang)){
					                    	$lang = 'vi';
					                    }else{
					                    	$lang = $this->arrParam['lang'];
					                    }
										$urlOptions = array('module'=>'products','controller'=>'index',
																'action'=>'detail',
																'cid'=> $value['menu_id'],
																'id'=>$value['id'],
																'tcat'=>$value['alias_name'],
																'title'=>$value['alias']);
										$linkDetail = $this->url($urlOptions,'products-detail');
						                $urlOptions2 = array('module'=>'products','controller'=>'index',
																'action'=>'order-detail',
																'tcat'=>$value['alias_name'],
																'title'=>$value['alias'],
																'cid'=> $value['menu_id'],
																'id'=>$value['id'],
																'lang'=>$lang);
										$linkCart = $this->url($urlOptions2,'products-order-detail');
	                        			if(($key+1)%4 == 0){
											$col = 'col4';
										}else{
											$col = 'col1';
										}
			                        ?>
		                        	<div class='box-right width-22 <?php echo $col?>'>
										<div class='bor-img-right'>
											<a href="<?php echo $linkDetail?>"><?php echo $picture?></a>
										</div>
										<div class='desc-right'>
											<h2><a href="<?php echo $linkDetail?>"><?php echo $name?></a></h2>
											<?php echo $price?>
											<?php echo $sale_off?>
											<?php echo $val_sell?>
											<a class='icon-right-cart' href="<?php echo $linkCart?>">Mua hàng</a>
										</div>
									</div>
		                            <?php 
		                        		}
		                        	?>
		                        </div>
		                        <?php
		                        	} 
		                        ?>
		                    </div>
					</div>
                    
                    
                        	
                    	
	</div>
</div>

<script type="text/javascript">
	function fancyBox(elem){
		elem = $(elem);
		if (!elem.data("fancybox")) {
			elem.data("fancybox", true);
			elem.fancybox({
				'titleShow' 	: false,
				'transitionIn'	: 'elastic',
				'transitionOut'	: 'elastic',
				'centerOnScroll': true
			}).trigger('click');
		}
		return false; 
	}
	$('.overlay').click(function(){
		$('#fancybox-wrap').hide();
	});
</script>
<script>
	$(document).ready(function() {
		$(".submit-com").click(function(){
			$(".comment").show("slow");
		});
		$('.close').click(function(){
			$('.comment').hide("slow");
		});
                $( "#dialog" ).dialog({
                    autoOpen: false,
                    show: {
                            effect: "blind",
                            duration: 1000
                    },
                    hide: {
                            effect: "explode",
                            duration: 1000
                    },
                    maxHeight: 500,
                    minWidth: 767
                });

              $( "#opener" ).click(function() {
                $( "#dialog" ).dialog( "open" );
              });
		
	});
</script>

