<div class='right width-78'>
	<div class='box-right-pro width-100'>
		<div class='sub-box-right'><span class='icon-right'><img src="<?php echo $this->imgUrl ?>/icon/icon-sub-right.png"></span><p>Đặt hàng</p></div>
	<div class="detail cnt-right mar-top-5 width-96 order-cart">
		<div class="order-cart">
                    		<table cellpadding="0" cellspacing="0">
                    			<tr class="sub-cart">
                    				<td class="first">Tên sản phẩm</td>
                    				<td>Quy cách</td>
                    				<td width="50">Số lượng</td>
                    				<td width="80">Giá gốc (Vnd)</td>
                    				<td width="80">Giá bán(Vnd)</td>
                    				<td width="80">Tổng tiền</td>
                    			</tr>
                    			<?php
	                            	$cart = $this->cart;
	                            	$linkOrder = $this->baseUrl('/products/index/order');
	                            	$linkUpdate = $this->baseUrl('/products/index/add-item');
	                            	$linkBack = $this->baseUrl('/products/index/index');
	                            	if(count($this->Items)>0){
	                            		$totalPrice = 0;
	                            		foreach ($this->Items as $key => $val){
	                            		$name 		= $val['name_pro'];
	                            			$size 		= $val['size'];
	                            			$id 		= $val['id'];
	                            			$menu_id	= $val['menu_id'];
	                            			include 'includes/sale.php';
	                            			
						            		$quantity 	= $cart[$id];
	                            			$total 		= 0;
	                            			
	                            			$sale 	= $val['sale'];
	                            			$menu_id	= $val['menu_id'];
											include 'includes/sale.php';
											$price 		= $val['price'];
											
	                            			$sale_pro 		= $val['selloff'];
											if (empty($sale_pro)){
												$sale_pro 		= $val['price'];
												$total 			= $quantity * $sale_pro; 
			                          			$total 			=  $total;
											}
											
											if(!empty($val['val_sell']) || $val['val_sell'] != 0){
												$val_sell_pro = $val['val_sell'];
												$sale_pro = $val['selloff'];
												$total 		= $quantity * $sale_pro; 
			                          			$total 		=  $total;
											}
                                			if((!empty($val['sell_pro']) || $val['sell_pro'] != 0) && (empty($val['val_sell']) || $val['val_sell'] == 0)){
                                				$val_sell_pro 	= $val['sell_pro'] ;
                                				$sale_pro 		= $val['price'] - ($val['price'] * $val['sell_pro']/100);
                                				$total 			= $quantity * $sale_pro; 
			                          			$total 			=  $total;
											}
											if((empty($val['sell_pro']) || $val['sell_pro'] == 0) && (empty($val['val_sell']) || $val['val_sell'] == 0)){
												if(!empty($sale)){
													$val_sell_pro 	= $sale ;
													$sale_pro 		= $val['price'] - ($val['price'] * $sale/100);
													$total 			= $quantity * $sale_pro; 
				                          			$total 			=  $total;
												}
											}
			                          		$totalPrice 	+= $total;
			                          		$filter = new Zend_Filter();
											$multiFilter = $filter	->addFilter(new Zend_Filter_StringToLower(array('encoding'=>'UTF-8')))
																 	->addFilter(new Zend_Filter_StringTrim())
										 						 	->addFilter(new Zend_Filter_Alnum(true))
										  						 	->addFilter(new Zend_Filter_PregReplace(array('match'=>'#\s+#','replace'=>'-')))
										  							->addFilter(new Zend_Filter_Word_SeparatorToDash())
										  							->addFilter(new Zendvn_Filter_RemoveCircumflex());
										  
			                          		$linkDetial = $this->baseUrl('/products/index/detail/cid/' . $val['cat_id'] 
		                          									 . '/tcat/' . $filter->filter($val['category_name']) 
		                          									 . '/id/' . $val['id'] . '/title/' . $filter->filter($val['name']));
	
		                          		    $itemProduct = 'itemProduct[' . $val['id'] . ']';				 
	                            			$itemProduct = $this->formText($itemProduct,$quantity,
	                            											array('style'=>'width: 35px; text-align: center; font-size: 11px; background-color:#FFC;padding: 2px 2px;'));

	                            ?>
                    			<tr>
                    				<td class="first" style="text-align: left;"><strong><a href="<?php echo $linkDetail;?>" class="itemLink color-blue" target="_blank"><?php echo $name;?></a></strong></td>
                    				<td><?php echo $size;?></td>
                    				<td><?php echo $itemProduct;?></td>
                    				<td><?php echo number_format($price)?></td>
                    				<td class='pri_sale'><?php echo number_format($sale_pro)?></td>
                    				<td><?php echo number_format($total,null)?></td>
                    				<input type="hidden" value="<?php echo $this->arrParam['action']; ?>" name="hidden" />
                    			</tr>
                    			<?php 
                            		}
                            	}
                         	?> 
                    		</table>
                    		<p class="total-money">Tổng số tiền thanh toán : <strong><?php echo number_format($totalPrice,null) . ' (VND)';?></strong></p>
                    		
                    	</div>
                        <?php
                        	$user 			= $this->User;
                        	$valFullname 	= $this->arrParam['full_name'];
                        	$valEmail 		= $this->arrParam['email'];
                        	$valAddress 	= $this->arrParam['address'];
                        	$valPhone 		= $this->arrParam['phone']; 
                        	if(!empty($user)){
                        		$valFullname = $user['first_name'] . ' ' . $user['last_name'];
                        		$valEmail = $user['email'];
                        		$valAddress = $user['address'];
                        		if (empty($valAddress)) $valAddress = $this->arrParam['address'];
                        		$valPhone = $user['phone']; 
                        		if (empty($valPhone)) $valPhone = $this->arrParam['phone'];
                        	}
                     		$full_name 	= $this->formText('full_name',$valFullname,array('style'=>'width: 60%;','class'=>'text'));
                     		$email 		= $this->formText('email',$valEmail,array('style'=>'width: 60%;','class'=>'text'));
                     		$phone 		= $this->formText('phone',$valPhone,array('style'=>'width: 60%;','class'=>'text'));
                     		$address 	= $this->formTextarea('address',$valAddress,array('rows'=>4,'style'=>'width: 90%;','class'=>'midium-text'));
                     		$shipping 	= $this->formTextarea('shipping',$this->arrParam['shipping'],array('rows'=>4,'style'=>'width: 90%;','class'=>'midium-text'));
                     		$comment 	= $this->formTextarea('comment',$this->arrParam['comment'],array('rows'=>4,'style'=>'width: 90%;','class'=>'midium-text'));
                     		
                     		$options 	= array(
                     							'Thanh toán trực tiếp',
                     							'Thanh toán chuyển khoản',
                     							'Thanh toán trả góp'
                     							);
							$payment 	= $this->formRadio('payment',$this->arrParam['payment'],null,$options, ' ');
							
                     		$submit		= $this->formSubmit('submit','Gửi thông tin',array("class"=>"submit"));
                     		//------------------------MESSAGES ERROR----------------------
                     		if(count($this->errors)>0){
									$errors = $this->errors;
								}
							?>
						<div class="info-cart mar-top-30">	
	                     	<form name="your-cart" id="your-cart" action="" method="post">
		                        <div class="lev">
					                 <span>Họ và tên: </span><?php echo $full_name;?>
					                 <div><?php if(!empty($errors['full_name'])):echo '<p class="msg_error">'.$errors['full_name'].'</p>';endif;?></div>
					            </div>
					            <div class="lev">
					                 <span>Email: </span><?php echo $email;?>
					                 <div><?php if(!empty($errors['email'])):echo '<p class="msg_error">'.$errors['email'].'</p>';endif;?></div>
					            </div>
					            <div class="lev">
					                 <span>Điện thoại: </span><?php echo $phone?>
					                 <div><?php if(!empty($errors['phone'])):echo '<p class="msg_error">'.$errors['phone'].'</p>';endif;?></div>
					            </div>
					            <div class="lev">
					                 <span>Địa chỉ: </span><?php echo $address;?>
					                 <div><?php if(!empty($errors['address'])):echo '<p class="msg_error">'.$errors['address'].'</p>';endif;?></div>
					            </div>
					            <div class="lev">
					                 <span>Giao hàng tại: </span><?php echo $shipping;?>
					                 <div><?php if(!empty($errors['shipping'])):echo '<p class="msg_error">'.$errors['shipping'].'</p>';endif;?></div>
					            </div>
					            <div class="lev">
					                 <span>Ghi chú: </span><?php echo $comment;?>
					                 <div><?php if(!empty($errors['comment'])):echo '<p class="msg_error">'.$errors['comment'].'</p>';endif;?></div>
					            </div>
					            <div class="lev payment">
					                 <p><b>CHỌN PHƯƠNG THỨC THANH TOÁN:</b></p>
					                 <?php echo $payment;?>
					            </div>
					            <div class="lev">
					             	<div><?php echo $submit;?></div>
					            </div>
					                             
	                        </form>
                        </div>
	</div>
	</div>
</div>