            	<?php
            		$items	= $this->Items;
                	foreach ($items as $key => $value){
                        	$cutTring 	= new Zendvn_File_CutTring();
							$name		= str_replace("\\","",$value['name']);
								
							$alt		= str_replace("\\","",$value['alt_seo']);
							if(empty($value['alt_seo'])) $alt = str_replace("\\","",$value['name']);
							
							$summary	= str_replace("\\","",$value['summary']);
							$summary	= $cutTring->cutTring(120, $summary, null);
							$price 		= '<p class="price-right-pro">' . number_format($value['price'],0) . ' VND</p>';
							
							$sale		= $value['sale'];
							$menu_id	= $value['menu_id'];
							include 'includes/sale.php';
							
							$val_sell 	= '';
							$sale_off 	= '';
							if ($value['selloff'] != 0){
								$sale_off	= '<p class="sale">' . number_format($value['selloff'],0) . ' VND</p>';
								$val_sell 	= '<div class="icon-sale">'. $value['val_sell'] .'%</div>';
							}
							$price 		= '<p class="price-right-pro">' . number_format($value['price'],0) . ' VND</p>';
							if($value['val_sell'] != 0){
								$price 	= '<p class="price-right-pro  line-through">' . number_format($value['price'],0) . ' VND</p>';
							}
							if ($sale != 0){
								$sale_off 	= $value['price'] - ($value['price']*$sale/100);
								$sale_off	= '<p class="sale">' . number_format($sale_off,0) . ' VND</p>';
								$price 		= '<p class="price-right-pro line-through">' . number_format($value['price'],0) . ' VND</p>';
								$val_sell 	= '<div class="icon-sale">'. $sale .'%</div>';
								if($value['val_sell'] != 0){
									$val_sell 	= '<div class="icon-sale">'. $value['val_sell'] .'%</div>';
									$sale_off	= '<p class="sale">' . number_format($value['selloff'],0) . ' VND</p>';
								}
							}
							
							if(!empty($value['picture'])){
								$linkImg	= FILES_URL . '/products/orignal/' . $value['picture'];
								$picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
							}else{
								$linkImg	= $this->imgUrl . '/no-image.jpg';
								$picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
							}
							
							$urlOptions = array('module'=>'products','controller'=>'index',
														'action'=>'detail',
														'cid'=> $value['menu_id'],
														'id'=>$value['id'],
														'tcat'=>$value['alias_name'],
														'title'=>$value['alias']);
							$linkDetail = $this->url($urlOptions,'products-detail');
							
							$urlOptions2 = array('module'=>'products','controller'=>'index',
														'action'=>'order-detail',
														'tcat'=>$value['alias_name'],
														'title'=>$value['alias'],
														'cid'=> $value['menu_id'],
														'id'=>$value['id'],
														'lang'=>$lang);
							$linkCart = $this->url($urlOptions2,'products-order-detail');
							if(($key+1)%4 == 0){
								$col = 'col4';
							}else{
								$col = 'col1';
							}
              ?>
              <div class="span4 row-pro">
                  <div class="thumbnail">
                    <a href="<?php echo $linkDetail?>"><?php echo $picture?></a>
                    <div class="caption">
                      <h2 class='title-pro'><a href="<?php echo $linkDetail?>"><?php echo $name?></a></h2>
                      <p></p>
                      <p><a class="btn btn-primary" href="<?php echo $linkDetail?>">Chi tiết</a> <a class="btn" href="<?php echo $linkCart?>">Đặt hàng</a></p>
                    </div>
                  </div>
              </div>
              <?php
              	} 
              ?>
              
