<div class='right width-78'>
<div class='box-right-pro width-100'>
		<div class='sub-box-right'>
			<span class='icon-right'><img src="<?php echo $this->imgUrl ?>/icon/icon-sub-right.png"></span>
			<p>Thông báo</p>
		</div>
		<div class="success">
			Quá trình gửi bình luận của bạn đã thành công, vui lòng đợi thời gian quản trị kiểm duyệt.
		</div>
	</div>
</div>
<?php
	header( "refresh:2;url=http://congtynem.com/vi" );
?>