<?php 
	$name 		= $this->formText('name',str_replace("\\","",$this->Item['name']),array('class'=>'txtmedium'));
	$id_name 	= $this->formText('id_name',str_replace("\\","",$this->Item['id_name']),array('class'=>'txtmedium'));
	$alias 		= $this->formText('alias',str_replace("\\","",$this->Item['alias']),array('class'=>'txtmedium'));
	$title_seo 	= $this->formText('title_seo',str_replace("\\","",$this->Item['title_seo']),array('class'=>'txtmedium'));
	$url 		= $this->formText('url',str_replace("\\","",$this->Item['url']),array('class'=>'txtmedium','readonly'=>'readonly'));
	$router 	= $this->formText('router',str_replace("\\","",$this->Item['router']),array('class'=>'txtmedium','readonly'=>'readonly'));
	$parent 	= $this->cmsSelect('parents',$this->Item['parents'],$this->tblCategory,array('style'=>'width:200px','size'=>10));
	$parent		= str_replace("\\","",$parent);
	
	$options2	= array($this->translate('--Select a type--'),
						$this->translate('Home'),
						$this->translate('News'),
						$this->translate('Products'),
						$this->translate('Service'),
						$this->translate('Contact'),
						$this->translate('About'),
						$this->translate('Recruitment'),
						$this->translate('Table price'),
						$this->translate('Collection'),
						$this->translate('Videos'),
					);
	$type 		= $this->formSelect('type',$this->Item['type'],array('style'=>'width:200px','size'=>10),$options2);
	
	$summary    = $this->formTextarea('summary',str_replace("\\","",$this->Item['summary']),array('rows'=>'10'));
	$description_html 	= $this->formTextarea('description_html',str_replace("\\","",$this->Item['description_html']),array('rows'=>'10'));									
	$keywords_html 		= $this->formTextarea('keywords_html',str_replace("\\","",$this->Item['keywords_html']),array('rows'=>'10'));
	$valSta 	= $this->Item['status'];
	if($valSta == ''){$valSta = 0;}
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$status 	= $this->formRadio('status',$valSta,null,$options, ' ');
	
	$options	= array(
						$this->translate('All'),
						$this->translate('Top'),
						$this->translate('Right'),
						$this->translate('Bottom'),
						$this->translate('Left')
					);
					
	$opti 	= array($this->translate('No'),$this->translate('Yes'));
	$special 	= $this->formRadio('special',$this->Item['special'],null,$opti, ' ');
									
	$positions	= $this->formSelect('positions',$this->Item['positions'],null,$options,null);
	$order 		= $this->formText('order',$this->Item['order'],array('class'=>'txtshort'));	
	$inputInfo 		= array('name'=>'picture');
	$imgArr 		= !empty($this->Item['picture'])?array( FILES_URL . '/product_category/images100x100/'.$this->Item['picture']):'';
	$image 	= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/category/images100x100/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));	
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium = $this->formHidden('current_stadium_picture',$this->Item['picture']);  
 	
	$Input 		= array(
						array('Label'=>$this->translate('Category name'),'input'=>$name,'info'=>0),
						array('Label'=>$this->translate('Alias'),'input'=>$alias,'info'=>0),
						array('Label'=>$this->translate('ID name'),'input'=>$id_name,'info'=>0),
						array('Label'=>$this->translate('Title SEO'),'input'=>$title_seo,'info'=>0),
						array('Label'=>$this->translate('Type Menu'),'input'=>$type,'info'=>0),
						array('Label'=>$this->translate('Url'),'input'=>$url,'info'=>0),
						array('Label'=>$this->translate('Router'),'input'=>$router,'info'=>0),
						array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>0),
						array('Label'=>$this->translate('Parent'),'input'=>$parent,'info'=>0),
						array('Label'=>$this->translate('Notes'),'input'=>$summary,'info'=>0),
						array('Label'=>$this->translate('Description HTML'),'input'=>$description_html,'info'=>0),
						array('Label'=>$this->translate('Keywords HTML'),'input'=>$keywords_html,'info'=>0),
						array('Label'=>$this->translate('Position'),'input'=>$positions,'info'=>0),
						array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
						array('Label'=>$this->translate('Special'),'input'=>$special,'info'=>0),
						array('Label'=>$this->translate('Order'),'input'=>$order,'info'=>0),
						);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        
                        <?php echo $errors;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input) .$current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>