<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
       	<?php echo $this->headTitle() ?>
       	<?php echo $this->headMeta() ?>
		<?php echo $this->headLink() ?>
		<?php echo $this->headScript() ?>
    </head>
<body>
	<div class="login">
		<div class="title"></div>
		<div class="box-login">
			<?php echo $this->layout()->content;?>
		</div>
	</div>
</body>
</html>
