<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$langTmp = $ssFilter['lang'];
	$lang = '';
	if(!empty($langTmp)){
		$lang = '/lang/' . $langTmp;
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblGroup_name 	= $this->cmsLinkSort($this->translate('Group name'),'g.group_name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
																			
	$lblOrder 		= $this->cmsLinkSort($this->translate('Order'),'g.order',$ssFilter,
										$this->imgUrl . '/icon',$action_link);	
										
	$lblMembers 		= $this->cmsLinkSort($this->translate('Member'),'members',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblId 		= $this->cmsLinkSort('ID','id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);	

	
	if($ssFilter['col'] != 'g.group_name'){		
		$linkOder =  $this->baseUrl($this->currentController . '/filter/type/order/col/g.group_name/by/DESC');
		$iconSort = $this->imgUrl . '/icon/arrow_down.png';
	}else{
		if($ssFilter['order'] == 'DESC'){
			$by = 'ASC';
			$iconSort = $this->imgUrl . '/icon/arrow_down.png';
		}else{
			$by = 'DESC';
			$iconSort = $this->imgUrl . '/icon/arrow_up.png';
		}		
		$linkOder =  $this->baseUrl($this->currentController . 
									'/filter/type/order/col/g.group_name/by/' . $by);
	}
	
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
?>
<form name="appForm" method="post" action="">
                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php echo $strSearch;?>
									</div>
								</div>	
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lblGroup_name ;?></th>
                                            <th width="89"><?php echo $this->translate('Status') ?></th>
                                            <th width="83">ACP</th>
                                            <th width="83"><?php echo $this->translate('Registed')?></th>
                                            <th width="86"><?php echo $lblOrder;?></th>						
                                            <th width="77"><?php echo $lblMembers;?></th>
                                            <th width="90"><?php echo $this->translate('Control')?></th>
                                            <th width="34"><?php echo $lblId;?></th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$group_name 	= $val['group_name'];
											
											$status 		= $val['status'];
											$created 		= $val['created'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												$status 	= $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive *'. $group_name . '*', $linkStatus, $id);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status 	= $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active *'. $group_name . '*', $linkStatus, $id);
											}
											
											$group_acp 		= $val['group_acp'];
											if($group_acp == 1){
												$linkAcp 		= $this->baseUrl($this->currentController . '/acp/type/0/id/' . $id);										
												$group_acp 		= $this->cmsAjaxButton('ajax-access-item', 'Access', 'No access *'. $group_name . '*', $linkStatus, $id);
											}else{
												$linkAcp	 	= $this->baseUrl($this->currentController . '/acp/type/1/id/' . $id);										
												$group_acp 		= $this->cmsAjaxButton('ajax-noaccess-item', 'No Access', 'Access *'. $group_name . '*', $linkStatus, $id);
											}
											
											$members 		= $val['members'];
											$order			= $this->formText('items['.$id.']',$val['order'],array('class'=>'order'));
											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id . $lang);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/'. $id . $lang );
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete =  $this->cmsAjaxButton('ajax-delete-item', 'Delete Item', 'Delete *'. $group_name . '*', $linkDelete, $id);
										
											$strIconButton	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
											$cls = 'row0';
											if($key%2 != 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="even <?php echo $cls;?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><a href="<?php echo $linkEdit?>"><?php echo $group_name;?></a></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $group_acp;?></td>
                                        <td align="center"><?php echo $created;?></td>
                                        <td align="center"><?php echo $order;?></td>
                                        <td align="center"><?php echo $members;?></td>
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>