<?php 
	$group_name 	= $this->Item['group_name'];
	
	$link_avatart	= FILES_URL . "/group/images100x100/". $this->Item['avatar'];
	$img_avatar		= '<img src="'. $link_avatart .'" alt=""/>';
	
	$link_ranking	= FILES_URL . "/group/images100x100/". $this->Item['ranking'];
	$img_ranking	= '<img src="'. $link_ranking .'" alt=""/>';
	
	$group_acp			= $this->Item['group_acp'];
	if($group_acp == 1){												
		$group_acp = $this->cmsIconButton('Admin Control', $this->imgUrl . '/icon/active.png') . " Admin Control";
	}else{
		$group_acp = $this->cmsIconButton('No Admin Control', $this->imgUrl . '/icon/inactive.png') . " No Admin Control";
	}
			
	$created_by 	= $this->Item['user_name'];
	$created	 	= $this->Item['created'];
		
	$status			= $this->Item['status'];
	if($status == 1){												
		$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png') . " Active";
	}else{
		$status = $this->cmsIconButton('Inactive', $this->imgUrl . '/icon/inactive.png') . " Inactive";
	}	
	$order 			= $this->Item['order'];
	
	$Input = array(
					array('Label'=>$this->translate('Group name'),'input'=>$group_name,'info'=>1),
					array('Label'=>$this->translate('Avatar'),'input'=>$img_avatar,'info'=>1),
					array('Label'=>$this->translate('Ranking'),'input'=>$img_ranking,'info'=>1),
					array('Label'=>$this->translate('ACP'),'input'=>$group_acp,'info'=>1),
					array('Label'=>$this->translate('Created by'),'input'=>$created_by,'info'=>1),
					array('Label'=>$this->translate('Created'),'input'=>$created,'info'=>1),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>1),
					array('Label'=>$this->translate('Order'),'input'=>$order,'info'=>1),
					);
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Item Detail</div>
								<div class="adminheader">Item Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input);?>                              
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>