<?php 
	$name 			= $this->formText('name',$this->Item['name'],array('class'=>'txtmedium'));
	$url 			= $this->formText('url',$this->Item['url'],array('class'=>'txtmedium'));
	$options 		= array($this->translate('Inactive'),$this->translate('Active'));
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');	
	$inputInfo 		= array('name'=>'picture');
	$imgArr 		= !empty($this->Item['picture'])?array( FILES_URL . '/slide/images100x100/'.$this->Item['picture']):'';
	$image 	= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/slide/images100x100/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));	
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium = $this->formHidden('current_stadium_picture',$this->Item['picture']); 
 	
 	$note = '<div class="note-slide">Kích thước hình ảnh là: 480 x 260 (px) - Min: 10KB & Max: 5000KB</div>';
 	
	$Input 		= array(
						array('Label'=>$this->translate('Title'),'input'=>$name,'info'=>0),
						array('Label'=>$this->translate('Url'),'input'=>$url,'info'=>0),
						array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>0),
						array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
						array('Label'=>$this->translate('Note'),'input'=>$note,'info'=>0),
						);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input) .$current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>