<?php
	$title 			= str_replace("\\","",$this->Item['title']);
	$content		= str_replace("\\","",$this->Item['content']);
	$status			= $this->Item['status'];
	if($status == 1){												
		$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png') . " Active";
	}else{
		$status = $this->cmsIconButton('Inactive', $this->imgUrl . '/icon/inactive.png') . " Inactive";
	}
	
	$featured			= $this->Item['featured'];
	if($featured == 1){												
		$featured = $this->cmsIconButton('Active', $this->imgUrl . '/icon/featured.png') . " Active";
	}else{
		$featured = $this->cmsIconButton('Inactive', $this->imgUrl . '/icon/nofeatured.png') . " Inactive";
	}
	
	/*...........Picture............*/
  	$urlimage   = FILES_URL . '/about/images100x100/'. $this->Item['picture'];
  	$picture  = '<img src="' . $urlimage . '" width="" height="40">'; 	
	$Input = array(
					array('Label'=>$this->translate('Title'),'input'=>$title,'info'=>1),
					array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>1),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>1),
					array('Label'=>$this->translate('Featured'),'input'=>$featured,'info'=>1),
					array('Label'=>$this->translate('Content'),'input'=>$content,'style'=>'margin-left:174px'),
					);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<?php echo $this->partialLoop('rows.php',$Input) . $current_stadium ;?>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>