<?php 
	$name 			= $this->formText('name',str_replace("\\","",$this->Item['name']),array('class'=>'txtmedium'));
	$alias 			= $this->formText('alias',str_replace("\\","",$this->Item['alias']),array('class'=>'txtmedium'));
	$alt_seo 		= $this->formText('alt_seo',str_replace("\\","",$this->Item['alt_seo']),array('class'=>'txtmedium'));
	$title_seo 		= $this->formText('title_seo',str_replace("\\","",$this->Item['title_seo']),array('class'=>'txtmedium'));
	$picture 		= $this->formFile('picture',array('style'=>'width: 250px'));
	$price 			= $this->formText('price',$this->Item['price'],array('class'=>'txtmedium','style'=>'width: 194px'));
	$warranty 		= $this->formText('warranty',$this->Item['warranty'],array('class'=>'txtmedium'));
	$selloff 		= $this->formText('selloff',$this->Item['selloff'],array('class'=>'txtmedium','style'=>'width: 194px', 'readonly' => 'readonly'));
	$val_sell	= $this->formText('val_sell',str_replace("\\","",$this->Item['val_sell']),array('class'=>'txtmedium','style'=>'width: 194px'));
	$summary        = $this->formTextarea('summary',str_replace("\\","",$this->Item['summary']),array('rows'=>'5'));
	$description_html 	= $this->formTextarea('description_html',str_replace("\\","",$this->Item['description_html']),array('rows'=>'5'));									
	$keywords_html 		= $this->formTextarea('keywords_html',str_replace("\\","",$this->Item['keywords_html']),array('rows'=>'5'));	
	$GroupCategory = $this->cmsSelect('menu_id',$this->Item['menu_id'],$this->tblGroupCategory,
										array('style'=>'width:200px','size'=>20));
	$content		= $this->cmsReplaceString($this->Item['content']);
	$content		= $this->cmsEditor('content',str_replace("\\","",$content),array('toolbar'=>'Default','language'=>'vi'));
	
	$info			= $this->cmsReplaceString($this->Item['info']);
	$info			= $this->cmsEditor('info',str_replace("\\","",$info),array('toolbar'=>'Default','language'=>'vi'));
	
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$status 	= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	
	$options 	= array($this->translate('No'),$this->translate('Yes'));
	$special 	= $this->formRadio('special',$this->Item['special'],null,$options, ' ');
	
	$options 	= array($this->translate('No'),$this->translate('Yes'));
	$featured 	= $this->formRadio('featured',$this->Item['featured'],null,$options, ' ');
	
	
	$code		= $this->formText('code',str_replace("\\","",$this->Item['code']),array('class'=>'txtmedium'));
	$weight		= $this->formText('weight',str_replace("\\","",$this->Item['weight']),array('class'=>'txtmedium'));
	$author		= $this->formText('author',str_replace("\\","",$this->Item['author']),array('class'=>'txtmedium'));
	$translator	= $this->formText('translator',str_replace("\\","",$this->Item['translator']),array('class'=>'txtmedium'));
	$pages		= $this->formText('pages',str_replace("\\","",$this->Item['pages']),array('class'=>'txtmedium'));
	//$size		= $this->formText('size',str_replace("\\","",$this->Item['size']),array('class'=>'txtmedium'));
	$year		= $this->formText('year',str_replace("\\","",$this->Item['year']),array('class'=>'txtmedium'));
	$board		= $this->formText('board',str_replace("\\","",$this->Item['board']),array('class'=>'txtmedium'));
	$units		= $this->formText('units',str_replace("\\","",$this->Item['units']),array('class'=>'txtmedium'));
	$publisher		= $this->formText('publisher',str_replace("\\","",$this->Item['publisher']),array('class'=>'txtmedium'));
	
	
	/*...........Picture............*/
	$imgArr 		= !empty($this->Item['picture'])?array( FILES_URL . '/products/images100x100/'.$this->Item['picture']):'';
	//$image 	= $this->cmsUserAvatar($inputInfo, $imgArr);
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/products/images100x100/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));	
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium = $this->formHidden('current_stadium_picture',$this->Item['picture']); 

 	if(!empty($this->Item['photos'])){
 		$img	= json_decode($this->Item['photos']);
 		$photos = '<div class="list-photo">';
 		if(!empty($img)){
	 		foreach ($img as $valPhoto) {
	// 			echo $valPhoto;
	 			$urlimage   = FILES_URL . '/photos/orignal/'. $valPhoto;
	 			$urlDelete	= $this->imgUrl . '/icon_del.png';
		  		$imgimage  	= '<div class="photo">
		  							<img src="' . $urlimage . '" width="" height="40">
		  							<span title="'.$this->translate('Delete').'" class="delete"><img src="'.$urlDelete.'" alt="" /></span>' 
		  							. $this->formHidden('current_photo',$valPhoto) . 
		  						'</div>';
		  		$photos	.= $imgimage;
	 		}
 		}
	  	$photos  .= "</div><br/>" . $this->formFile('photos[]',array('multiple'=>'multiple')) ;
 	}else{
 		$photos 	= $this->formFile('photos[]',array('multiple'=>'multiple'));
 	}
	
	$Input = array(
					array('Label'=>$this->translate('Product name'),'input'=>$name,'info'=>0),
					array('Label'=>$this->translate('Alias'),'input'=>$alias,'info'=>0),
					array('Label'=>$this->translate('Alt SEO'),'input'=>$alt_seo,'info'=>0),
					array('Label'=>$this->translate('Title SEO'),'input'=>$title_seo,'info'=>0),
					array('Label'=>$this->translate('Category'),'input'=>$GroupCategory,'info'=>0),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
					array('Label'=>$this->translate('Special'),'input'=>$special,'info'=>0),
					array('Label'=>$this->translate('Featured'),'input'=>$featured,'info'=>0),
                    array('Label'=>$this->translate('Summary'),'input'=>$summary,'info'=>0),
                    array('Label'=>$this->translate('Description HTML'),'input'=>$description_html,'info'=>0),
					array('Label'=>$this->translate('Keywords HTML'),'input'=>$keywords_html,'info'=>0),
					array('Label'=>$this->translate('Info'),'input'=>$info,'style'=>'margin-left:174px')
	);
	
	$Input2 = array(
					array('Label'=>$this->translate('Code product'),'input'=>$code,'info'=>0),
					//array('Label'=>$this->translate('Size'),'input'=>$size,'info'=>0),
					array('Label'=>$this->translate('Warranty'),'input'=>$warranty,'info'=>0),
					//array('Label'=>$this->translate('Author'),'input'=>$author,'info'=>0),
					//array('Label'=>$this->translate('Translator'),'input'=>$translator,'info'=>0),
					//array('Label'=>$this->translate('Units Issued'),'input'=>$units,'info'=>0),
					array('Label'=>$this->translate('Publisher'),'input'=>$publisher,'info'=>0),
					//array('Label'=>$this->translate('Pages'),'input'=>$pages,'info'=>0),
					//array('Label'=>$this->translate('Weight'),'input'=>$weight,'info'=>0),
//					array('Label'=>$this->translate('Paperboard'),'input'=>$board,'info'=>0),
					//array('Label'=>$this->translate('Year production'),'input'=>$year,'info'=>0),
					array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>0),
					array('Label'=>$this->translate('Photo gallery'),'input'=>$photos,'info'=>0,'class'=>'form-photo'),
					array('Label'=>$this->translate('Price'),'input'=>$price,'info'=>0),
					array('Label'=>$this->translate('Sale Off'),'input'=>$selloff,'info'=>0),
					array('Label'=>$this->translate('Value sale (%)'),'input'=>$val_sell,'info'=>0),
					array('Label'=>$this->translate('Content'),'input'=>$content,'style'=>'margin-left:174px'),
	);
	
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
	$id	= $this->Item['id'];
?>
<script type="text/javascript">
 $(document).ready( function(){
	 	$('.delete').click(function(event){
			event.preventDefault();
			var name_photo = $(this).next().val();
			var url,data,id_pro;
			url = '<?php echo $this->baseUrl("products/admin-product/delete-photo") ?>';
			data = {'type':'delete-photo','name_photo':name_photo,'id':'<?php echo $id?>'};
			$(this).parents('.photo').load(url,data);
			$(this).parents('.photo').remove();
		});
					
	});

</script>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                            <div class="adminheader">
                            	<div id='temp-1' class="temp"><?php echo $this->translate('Information')?></div>
                            	<div id='temp-2' class="temp"><?php echo $this->translate('Detail product')?></div>
                            </div>							
							<?php 
								echo '<div class="form-1">' . $this->partialLoop('rows.php',$Input) . $current_stadium . '</div>' ;
								echo '<div style="display:none" class="form-2">' . $this->partialLoop('rows.php',$Input2) . $current_stadium . '</div>' ;
							?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>
<?php
	 $publisher = $this->Publisher;
	 $units = $this->Units;
?>  
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<script>
	$(function() {
		 var publisher = [
								<?php
									foreach ($publisher as $value) {
										echo '"'.$value['name'] .'",';
									} 
								?>
								];
		 var units = [
							<?php
								foreach ($units as $val) {
									echo '"'.$val['name'] .'",';
								} 
							?>
							];
		$( "#publisher" ).autocomplete({
			source: publisher
		});

		$( "#units" ).autocomplete({
			source: units
		});
		
		$('#temp-1').click(function(){
			$('.form-1').show();
			$('.form-2').hide();
		});
		$('#temp-2').click(function(){
			$('.form-2').show();
			$('.form-1').hide();
		});
	});
</script>