<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$langTmp = $ssFilter['lang'];
	$lang = '';
	if(!empty($langTmp)){
		$lang = '/lang/' . $langTmp;
	}
?>
<form name="appForm" method="post" action="">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $this->translate('Title')?></th>
                                            <th width="70"><?php echo $this->translate('Featured')?></th>
                                            <th width="70"><?php echo $this->translate('Status')?></th>
                                            <th width="90"><?php echo $this->translate('Control')?></th>
                                            <th width="34">ID</th>
                                        </tr>
                                    </thead>
									<?php
										foreach($this->Items as $key => $val){
											$id 		= $val['id'];
											$title 		= $val['title'];							
											$status 	= $val['status'];
											if ($status == 1) {
												$linkStatus = $this->baseUrl ( $this->currentController . '/status/type/0/id/' . $id );
												$status = $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive *'. $title . '*', $linkStatus, $id);
											} else {
												$linkStatus = $this->baseUrl ( $this->currentController . '/status/type/1/id/' . $id );
												$status = $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active *'. $title . '*', $linkStatus, $id);
											}
											
											$featured 			= $val['featured'];											
											if ($featured == 1) {
												$linkfeatured = $this->baseUrl ( $this->currentController . '/featured/type/0/id/' . $id );
												$featured = $this->cmsAjaxButton('ajax-featured-item', 'Featured', 'Nofeatured *'. $title . '*', $linkfeatured, $id);
											} else {
												$linkfeatured = $this->baseUrl ( $this->currentController . '/featured/type/1/id/' . $id );
												$featured = $this->cmsAjaxButton('ajax-nofeatured-item', 'Nofeatured', 'Featured *'. $title . '*', $linkfeatured, $id);
											}											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id .$lang);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $lang);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete =  $this->cmsAjaxButton('ajax-delete-item', 'Delete Item', 'Delete *'. $title . '*', $linkDelete, $id);
										
											$strIconButton	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
											
											$cls = 'row0';
											if($key%2 != 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="even <?php echo $cls?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><a href='<?php echo $linkEdit?>'><?php echo $title;?></a></td>
                                        <td align="center"><?php echo $featured;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>