<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$langTmp = $ssFilter['lang'];
	$lang = '';
	if(!empty($langTmp)){
		$lang = '/lang/' . $langTmp;
	} 
?>
<form name="appForm" method="post" action="">
						<!--Gắn thông số hiện tại vào form hidden-->
						<?php echo $this->formHidden('_url',$url);?>

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style="float: left">
										<?php echo $strSearch;?>
									</div>
									<div style="float: right">
										<?php echo $selectGroup;?>
									</div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $this->translate('Name') ?></th>
                                            <th width="150"><?php echo $this->translate('Phone') ?></th>
                                            <th width="150"><?php echo $this->translate('Job') ?></th>	
                                            <th width="150"><?php echo $this->translate('Nick') ?></th>
                                            <th width="100"><?php echo $this->translate('Type') ?></th>
                                            <th width="100"><?php echo $this->translate('Status') ?></th>
                                            <th width="86"><?php echo $this->translate('Order') ?></th>
                                            <th width="90"><?php echo $this->translate('Control') ?></th>
                                            <th width="34">ID</th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 		= $val['id'];
											$name 		= $val['name'];
											$phone 		= $val['phone'];
											$manage 	= $val['manage'];
											$nick  		= $this->formText('nick['.$id.']',$val['nick'],null);
											$type 		= $this->formSelect('type['.$id.']',$val['type'],array('style'=>'width:80px'),array('Yahoo','Skype'));
											$status 	= $val['status'];
											$order		= $this->formText('order['.$id.']',$val['order'],array('class'=>'order'));
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												//$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png',$linkStatus);
												$status = $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive *'. $name . '*', $linkStatus, $id);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status = $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active *'. $name . '*', $linkStatus, $id);
											}											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $lang);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $lang);
											$btnDelete =  $this->cmsAjaxButton('ajax-delete-item', 'Delete Item', 'Delete *'. $name . '*', $linkDelete, $id);
										
											$strIconButton	= $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
											$cls = 'row0';
											if($key%2 != 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="even <?php echo $cls?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><a href="<?php echo $linkEdit?>"><?php echo $name;?></a></td>
                                        <td align="center"><?php echo $phone;?></td>
                                       	<td align="center"><?php echo $manage;?></td>
                                        <td align="center"><?php echo $nick;?></td>
                                        <td align="center"><?php echo $type;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $order;?></td>
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>                                    
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>