<?php 
	$goup_id = $this->Item['group_id'];
	$user_name 			= $this->Item['user_name'];
	$email 				= $this->Item['email'];
	$first_name 		= $this->Item['first_name'];
	$last_name 			= $this->Item['last_name'];
	$birthday 			= $this->Item['birthday'];
	$tblGroup 			= $this->slbGroup[$goup_id];
	
	$status			= $this->Item['status'];
	if($status == 1){												
		$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png') . " Active";
	}else{
		$status = $this->cmsIconButton('Inactive', $this->imgUrl . '/icon/inactive.png') . " Inactive";
	}	
	$sign				= $this->Item['sign'];	
	//Avatar
	$link_avatar	= FILES_URL . "/users/images100x100/". $this->Item['user_avatar'];
	$user_avatar		= '<img src="'. $link_avatar .'" alt=""/>';
	$Input = array(
					array('Label'=>'User name','input'=>$user_name,'info'=>1),
					array('Label'=>'Avatar','input'=>$user_avatar,'info'=>1),
					array('Label'=>'Email','input'=>$email,'info'=>1),
					array('Label'=>'Group','input'=>$tblGroup,'info'=>1),
					array('Label'=>'Status','input'=>$status,'info'=>1),
					array('Label'=>'First name','input'=>$first_name,'info'=>1),
					array('Label'=>'Last name','input'=>$last_name,'info'=>1),
					array('Label'=>'Birthday','input'=>$birthday,'info'=>1),
					array('Label'=>'Sign','input'=>$sign,'info'=>1,'style'=>'margin-left:174px'),
					);
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

<script type="text/javascript">
	$(document).ready(function(){
		$(function() {
			var today = new Date();
			var year = today.getFullYear()-70;
			$("#birthday").datepick({
				minDate: new Date(year, 1 - 1, 25),
				yearRange: "-10:-70",
			    dateFormat: 'yyyy-mm-dd',
				showOn: "both"
			});
		});		
	});
</script>


                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                            <div class="adminheader">Item Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input);?>                              
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>