<?php
if (count ( $this->messageError ) > 0) {
	$errors = $this->formErrors ( $this->messageError, array ('id' => 'errors' ) );
}
?>
<div class="right width-75 float-right">
	<div class="group width-100">
		<?php
			$status	= $this->arrParam['status'];
			if ($status != 1){
		?>
		<div class="sub-right width-100">
			<p>Quên mật khẩu</p>
		</div>
		<div class="detail cnt-right mar-top-5 width-100">
		    <div class="login">
		    	<form name="appForm" method="post" action="" enctype="multipart/form-data">
					<div class="lev">
						<span class="color-blue">Tên đăng nhập</span>
						<?php echo $this->formText('user_name','');?>
						<p class="msg-err"><?php echo $this->messageError['user_name']?></p>
					</div>
					<div class="lev">
						<span class="color-blue">Email</span>
						<?php echo $this->formText('email','');?>
						<p class="msg-err"><?php echo $this->messageError['email']?></p>
					</div>
					<div class="lev">
						<input class="submit" type="submit" name="submit" value="Gửi" />
					</div>
				</form>
		    </div>
	    </div>
	    <?php
			}else{
				echo "<p class='note'>Quá trình gửi yêu cầu thành công, vui lòng kích hoạt email để nhận mật khẩu mới.</p>";
			} 
	    ?>
	</div>
</div>
