<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Công Ty Nệm</title>
        <?php echo $this->headTitle()?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <?php echo $this->headScript() ?>
    <body>
    <section id='header-top'>
        <?php include_once 'html/header.php';?>
    </section>
    <section id="header">
        <?php include_once 'html/header-sidebar.php';?>
    </section> 
    <section id="slideshow">
        <?php include_once 'html/slideshow.php';?>
    </section>
    <section id="product-category">
        <?php include_once 'html/main-category.php';?>
    </section>
    <section>
        <?php include_once 'html/footer.php';?>
    </section>
    </body>
</html>
