<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headTitle()?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&language=vi"></script>
        <?php echo $this->headScript() ?>
    <body>
        <section id='header-top'>
            <?php include_once 'html/header.php'; ?>
        </section>
        <section id="header">
            <?php include_once 'html/header-sidebar.php';?>
        </section>
        <section id="product-detail">
            <?php include_once 'html/product-detail.php';?>
        </section>
        <section id="product-detail">
            <?php include_once 'html/footer.php';?>
        </section>
    </body>
</html>