<!DOCTYPE html>
<html>
    <head>
        <title>Công ty nệm | đại lý nệm | phân phối nệm</title>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="<?php echo $this->cssUrl . '/installment.css' ?>" rel="stylesheet">
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&language=vi"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>
        <?php echo $this->headScript() ?>
         <script src="<?php echo $this->jsUrl?>/jquery.wallform.js"></script>
         <script src="<?php echo $this->jsUrl?>/installment.js"></script>
    </head>
    <body>
        <section>
            <?php include_once 'html/header.php'; ?>
        </section>
        <div class="installment" >
            <h2 class="title-installment">Lợi ích khi mua tra góp</h2>
            <div class="menu-installment">
                <img src="<?php echo $this->imgUrl ?>/tragop.jpg">
            </div>
            <?php $val = $this->Items ?>
            <div class="thutuc-installment">
                <div class="hinh-installment">
                    <p><img src="<?php echo FILES_URL . '/products/images450x450/' . $val['picture'] ?>" alt="" width='240'></p>
                </div>
                <div class="thongtin-installment">
                    <div class="thongtin1-itm">
                        <p style="font-size: 17px; font-weight: bold; margin-top: 10px; margin-bottom: 9px;"><?php echo $val['name'] ?></p>
                        <span style="font-size: 23px; font-weight: bold; color: red;">
                            GIÁ: 
                            <strong id='price'><?php
                                if ($val['selloff'] > 0)
                                    echo number_format($val['selloff'], 0);
                                else
                                    echo number_format($val['price'], 0);
                                ?></strong>đ
                        </span>
                        <div class="thongtin2-itm">
                            <select class="tra-truoc-itm" id='tra-truoc-itm'>
                                <?php
                                if ($val['publisher'] == "Nệm Wean")
                                    echo '<option selected value="0">Trả trước 0%</option>';
                                ?>
                                <option value="10">Trả trước 10%</option>
                                <option value="20">Trả trước 20%</option>
                                <option value="30">Trả trước 30%</option>
                                <option value="40">Trả trước 40%</option>
                            </select>
                            <i class="fa fa-arrow-right"></i>
                        </div>
                        <div class="thongtin2-itm">
                            <select class="tra-truoc-itm" id='gop-itm'>
                                <option value="6">Kỳ hạn vay 6 tháng (Góp tháng)</option>
                                <option value="9">Kỳ hạn vay 9 tháng (Góp tháng)</option>
                                <option selected value="12">Kỳ hạn vay 12 tháng (Góp tháng)</option>
                                <option value="15">Kỳ hạn vay 15 tháng (Góp tháng)</option>
                                <option value="18">Kỳ hạn vay 18 tháng (Góp tháng)</option>
                            </select>
                            <i class="fa fa-arrow-right"></i>
                        </div>
                        <div class="thongtin2-itm">
                            <select class="tra-truoc-itm">
                                <option value="nomal">Lãi Suất</option>
                                <option value="1">HDF Hoàn tiền đến 3 triệu</option>
                            </select>
                            <i class="fa fa-arrow-right"></i>
                        </div>

                        <div class="gocvalai">
                            <span class="title">Tổng gốc và Lãi:</span>
                            <i class="fa fa-arrow-right"></i>
                        </div>
                        <div class="lienhetuvan">
                            <p style="margin-top: 8px;; margin-left: 45px;">
                                Vui lòng liên hệ <strong style="color: red;">0917 311 001</strong> để được tư vấn
                            </p>
                        </div>

                    </div>


                    <div class="col-itm">
                        <div class="col1-itm">
                            <div class="nganhang-itm">
                                <p class="ace"><img src="<?php echo $this->imgUrl ?>/acs.png" alt=""></p>
                            </div>
                            <div class="gia-tragop-itm">
                                <div class="col3-itm" id='tratruoc-acs'></div>
                                <div class="col3-itm" id='gop-acs'></div>
                                <div class="col3-itm">
                                    <?php
                                    if ($val['publisher'] == "Nệm Wean")
                                        echo '0%';
                                    else
                                        echo '<span id="laixuat-acs">2.45<span>';
                                    ?>
                                </div>
                                <div class="col3-itm" id='tong-acs'>6.747.000đ</div>
                            </div>
                            <div>
                                <button class="buttom-itm" data-toggle="modal" data-target=".buy-now" >Chọn ACS</button>
                            </div>
                        </div>
                        <div class="col1-itm">
                            <div class="nganhang-itm">
                                <p><img src="<?php echo $this->imgUrl ?>/HDFinance.png" style="width: 178px; margin-top: -4px;" alt=""></p>
                            </div>
                            <div class="gia-tragop-itm" style="margin-top: 35px;">
                                <div class="col3-itm">Đang Triển Khai</div>
                                <div class="col3-itm">0</div>
                                <div class="col3-itm">0</div>
                                <div class="col3-itm">0</div>
                            </div>
                            <div>
                                <button class="buttom-itm">Chọn HD</button>
                            </div>
                        </div>
                        <div class="col1-itm">
                            <div class="nganhang-itm" >
                                <p><img src="<?php echo $this->imgUrl ?>/sacombank.png"></p>
                            </div>
                            <div class="gia-tragop-itm">
                                <div class="col3-itm" id='tratruoc-sacombank'>Đang Triển Khai</div>
                                <div class="col3-itm">0</div>
                                <div class="col3-itm">0</div>
                                <div class="col3-itm">0</div>
                            </div>
                            <div>
                                <button class="buttom-itm">Chọn PPF</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tragop-itm">
                <div class="tragop-col-itm">
                    <div class="tragop-col-itm1">Phí trả chậm</div>
                    <div class="tragop-col-itm2"><img src="<?php echo $this->imgUrl ?>/acs.png" alt=""></div>
                </div>
                <div class="tragop-col-itm">
                    <div class="tragop-col-itm1 boder-itm">Đơn giản, lãi suất thấp</div>
                    <div class="tragop-col-itm2"><img src="<?php echo $this->imgUrl ?>/HDFinance.png" alt=""></div>
                </div>
                <div class="tragop-col-itm">
                    <div class="tragop-col-itm1">Thủ tục đơn giản</div>
                    <div class="tragop-col-itm2"><img src="<?php echo $this->imgUrl ?>/sacombank.png" alt=""></div>
                </div>
            </div>

            <div>
                <table>
                    <tr class="itm-tr">
                        <td class="itm-td-tths"></td>
                        <td class="itm-td-tths">
                            thủ tục - hồ sơ
                        </td>
                        <td class="itm-td-tths"></td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Tuổi</strong>
                            <div>Tuổi 21 - 60 (Sinh viên từ 18 tuổi trở lên)</div>
                        </td>
                        <td class="itm-td">
                            <div>Tuổi 19 - 60</div>
                        </td>
                        <td class="itm-td">
                            <div>20 - 55</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Giấy tờ bạn cần chuẩn bị:</strong>
                            <div>CMND + Hộ khẩu/KT3 + Hóa đơn tiền điện/nước/internet + một số điện thoại bàn</div>
                        </td>
                        <td class="itm-td">
                            <div>Số tiền vay < 10 triệu: CMND + Bằng lái
                                Số tiền vay > 10 triệu: CMND + Hộ khẩu + hóa đơn điện/nước</div>
                        </td>
                        <td class="itm-td">
                            <div>CMND + Bằng lái (nếu số tiền vay < 10 triệu)
                                CMND + Hộ khẩu (nếu số tiền vay > 10 triệu)</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Thời gian duyệt hồ sơ:</strong>
                            <div>4 giờ</div>
                        </td>
                        <td class="itm-td">
                            <div>30 phút</div>
                        </td>
                        <td class="itm-td">
                            <div>30 phút</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Tỉ lệ duyệt hồ sơ thành công:</strong>
                            <div>
                                60%</div>
                        </td>
                        <td class="itm-td">
                            <div>80%</div>
                        </td>
                        <td class="itm-td">
                            <div>80%</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Phương thức thanh toán:</strong>
                            <div>Chuyển khoản ngân hàng vào tài khoản công ty ACS (có phí), hoặc nộp trực tiếp miễn phí tại bất kì siêu thị nào của BKC</div>
                        </td>
                        <td class="itm-td">
                            <div> <strong>Miễn phí</strong> phí thanh toán hàng tháng qua bưu điện và ngân hàng</div>
                        </td>
                        <td class="itm-td">
                            <div>Chuyển khoản ngân hàng vào tài khoản công ty PPF (có phí), Hoặc nộp trực tiếp miễn phí tại bất kì siêu thị nào của BKC</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                            <strong>Tỉnh thành hỗ trợ:</strong>
                            <div>Hồ Chí Minh, Hà Nội, Đà Nẵng, Đồng Nai, Bình Dương, Biên Hòa, Cần Thơ...</div>
                        </td>
                        <td class="itm-td">
                            <div>Hồ Chí Minh, Hà Nội, Đà Nẵng, Đồng Nai, Bình Dương, Biên Hòa, Cần Thơ...</div>
                        </td>
                        <td class="itm-td">
                            <div>Hồ Chí Minh, Hà Nội, Đà Nẵng, Đồng Nai, Bình Dương, Biên Hòa, Cần Thơ...</div>
                        </td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td-tths"></td>
                        <td class="itm-td-tths">
                            khuyễn mãi đặc biệt
                        </td>
                        <td class="itm-td-tths"></td>
                    </tr>

                    <tr class="itm-tr">
                        <td class="itm-td">
                        </td>
                        <td class="itm-td">
                            <div><strong>- Chương trình lãi suất ưu đãi 1,49%:</strong> Chỉ cần chứng minh thu nhập và  địa chỉ cư trú <br>
                                <strong>- Chương trình Hoàn tiền:</strong> Hoàn tiền lên đến 3 triệu đồng nếu thanh toán đầy đủ và đúng hạn. <br>
                                <strong>- Chương trình gói sản phẩm:</strong> Mua cùng lúc 6 sản phẩm khác nhau.<br>
                                <strong>- Chương trình bảo hiểm:</strong> Miễn phí 100% Bảo hiểm khoản vay trong suốt thời gian vay.
                            </div>
                        </td>
                        <td class="itm-td">
                            <div>
                                <strong>Miễn phí trả góp cuối tháng (Cả vốn lẫn lãi)</strong><br>
                                - KM: Được hưởng tất cả khuyến mãi (nếu có)
                                - Điều kiện: KH thanh toán đầy đủ, đúng hạn.
                            </div>
                        </td>
                    </tr>

                </table>
            </div>
        </div>
        <section>
            <section id="footer">
                <?php include_once 'html/footer.php';?>
            </section>
        </section>
        <!-------------------------MODAL MUA HÀNG---------------------------------->
        <div class="modal fade buy-now" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="ppu_header">
                        <p class="ppu_h_title">ĐẶT HÀNG - NGHE TƯ VẤN MIỄN PHÍ</p>
                        <p class="ppu_h_noti">(Không mua không sao)</p>
                    </div>
                    <div class="ppu_tabs_main">
                        <!-- clear html when click list maps, changer to div.ppu_ss_main -->
                        <!-- TAB MENU-->
                        <div class="ppu_tab">
                            <div class="ppu_tabshop current" key="1"><span>Đặt giữ hàng tại shop </span></div>
                            <div class="ppu_tabhome" key="2"><span>Giao hàng miễn phí tại nhà </span></div>
                        </div>
                        <!-- #1 TAB HOME-->
                        <div class="ppu_content" id="ppu-tab-home">
                            <div class="ppu_tab_content clearfix">
                                <!-- LEFT TAB-->
                                <div class="ppu_tab_left">
                                    <div class="ppu_tab_left_content">
                                        <div class="clearfix">
                                            <div class="ppu_tab_proimg">
                                                <img src="<?php echo FILES_URL . '/products/images100x100/' . $val['picture'] ?>" alt="" style="margin-left: -40px;">
                                            </div>
                                            <div class="tab_pro_info">
                                                <ul>
                                                    <li><?php echo $val['name'] ?></li>
                                                    <li>
                                                        Giá chỉ 
                                                        <?php
                                                        if ($val['selloff'] == 0)
                                                            echo '<strong style="color:red; font-size:17px">' . number_format($val['price'], 0) . '</strong>';
                                                        else
                                                            echo '<strong style="color:red; font-size:17px">' . number_format($val['selloff'], 0) . '</strong>';
                                                        ?>
                                                        đ
                                                    </li>
                                                    <li>Trả trước: <span id="tratruoc"></span></li>
                                                    <li>Kỳ hạn: <span id="kyhan"></span></li>
                                                    <li>Lãi suất: <span id="laisuat"></span></li>
                                                </ul>
                                                <div class="ppu_tab_pro_sales">
                                                    <div class="ppu_tab_psales">Khuyến mãi đi kèm</div>
                                                    <div class="ppu_tab_color_img">
                                                        <img class="ppu_tab_cimg_arow" src="public/files/products/images100x100/<?php echo $val['picture'] ?>">
                                                        <div class="ppu_tab_cimg_main">
                                                            <p style="font-size: 14px; line-height: 24px; color: red; font-family:tahoma,geneva,sans-serif;">Đặt ngay tặng kèm:</p>

                                                            <ul>
                                                                <li style="font-size: 14px; line-height: 24px; color: red; font-family:tahoma,geneva,sans-serif;">Phiếu mua hàng phụ kiện&nbsp;<b>500.000đ</b></li>
                                                            </ul>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="ppu_add_shop">
                                                <p class="ppu_add_shop_title">Chọn địa chỉ Shop</p>
                                                <div class="ppu_local_box clearfix">
                                                    <div class="ppu_adds_city">
                                                        <select id="ddlCity" name="city" class="sl-item-2 list-city">
                                                            <option selected="selected" value="0">Chọn Tỉnh</option>
                                                            <option value="1">TP Hồ Chí Minh</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="ppu_adds_list">
                                                    <ul id="ddlShop">
                                                        <li title="156 Đặng Văn Bi - Q. Thủ Đức" class="item-shop item-shop-1" onclick="showMap(10.846783, 106.760974, 1,<?php echo $val['id'] ?>)">156 Đặng Văn Bi - Q. Thủ Đức<p></p></li>
                                                        <li title="974 Kha Vạn Cân - Q. Thủ Đức" class="item-shop item-shop-2" onclick="showMap(10.857691, 106.757349, 2,<?php echo $val['id'] ?>)">974 Kha Vạn Cân - Q. Thủ Đức<p></p></li>
                                                        <li title="263 Lê Văn Việt - Q. 9" class="item-shop item-shop-3" onclick="showMap(10.844651, 106.790530, 3,<?php echo $val['id'] ?>)">263 Lê Văn Việt - Q. 9<p></p></li>
                                                    </ul>
                                                </div>
                                                <div class="ppu_tab_lmap_title lmap-1" style="display:none">
                                                    <img src="<?php echo $this->imgUrl ?>/ppu_icon_map.png">
                                                    <span id="chooseShopStoreID">Showroom 156 Đặng Văn Bi - Q. Thủ Đức</span>
                                                    <span class="ppu_tab_lmap_close">
                                                        <img src="<?php echo $this->imgUrl ?>/ppu_close_map.png" onclick="hideMap()">
                                                    </span>
                                                </div>
                                                <div class="ppu_tab_lmap_title lmap-2" style="display:none">
                                                    <img src="<?php echo $this->imgUrl ?>/ppu_icon_map.png">
                                                    <span id="chooseShopStoreID">Showroom 974 Kha Vạn Cân - Q. Thủ Đức</span>
                                                    <span class="ppu_tab_lmap_close">
                                                        <img src="<?php echo $this->imgUrl ?>/ppu_close_map.png" onclick="hideMap()">
                                                    </span>
                                                </div>
                                                <div class="ppu_tab_lmap_title lmap-3" style="display:none">
                                                    <img src="<?php echo $this->imgUrl ?>/ppu_icon_map.png">
                                                    <span id="chooseShopStoreID">Showroom 263 Lê Văn Việt - Q. 9</span>
                                                    <span class="ppu_tab_lmap_close">
                                                        <img src="<?php echo $this->imgUrl ?>/ppu_close_map.png" onclick="hideMap()">
                                                    </span>
                                                </div>
                                                <div id="map-google-<?php echo $val['id'] ?>" class="map-google" style="width: 400px;  height: 258px; position: absolute; display: none;"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- RIGHT TAB-->
                                <div class="ppu_tab_right">
                                    <div class="ppu_tab_right_box">
                                        <input type="hidden" value="<?php echo $val['id'] ?>" name="id" id="id">
                                        <input type="hidden" value="" name="address" id="diachigiaohang-<?php echo $val['id']?>">
                                        <span style="color:red">(*) Bạn buộc phải nhập thông tin vào!</span>
                                        <p class="pform-inline">
                                            <input name="full_name" id="full_name" class="ppu_rtxt" type="text" placeholder="Họ tên bạn" data-rule-required="true">
                                            <i>*</i>
                                        </p>
                                        <p class="pform-inline">
                                            <input id="phoneMuaHang" name="phone" id="phone" class="ppu_rtxt" type="text" placeholder="Số điện thoại" data-rule-required="true">
                                            <i>*</i>
                                        </p>
                                        <div id='preview'></div>
                                        <form id="imageform" method="post" enctype="multipart/form-data" action='default/user-upload/index' style="clear:both">
                                            Upload image:
                                            <div id='imageloadstatus' style='display:none'><img src="<?php echo $this->imgUrl?>/loader.gif" alt="Uploading...."/></div>
                                            <div id='imageloadbutton'>
                                                <input type="file" name="photos[]" id="photoimg" multiple="true" />
                                            </div>
                                        </form>
                                        <textarea name="address" id="address" class="ppu_rtextarea" placeholder="Địa chỉ giao hàng"></textarea>
                                        <div class="ppu_tab_tt_price">Tổng giá trị đơn hàng: <span class="textTotalMoney">
                                                <?php
                                                if ($val['selloff'] > 0)
                                                    echo number_format($val['selloff'], 0);
                                                else {
                                                    echo number_format($val['price'], 0);
                                                }
                                                ?>
                                            </span>&nbsp;đ</div>
                                        <button class="ppu_rbnt_submit" onclick="traGop()"> Đặt Ngay</button>

                                    </div>
                                </div>
                            </div>

                            <!-- BOTTOM TAB-->
                            <div class="ppu_bottom_noti">
                                <p>Chúng tôi sẽ liên hệ với bạn trong vòng <strong>1 tiếng</strong>  và cam kết giao hàng miễn phí trong <strong>1 ngày</strong>.</p>
                                <p class="ppu_bt_call">Tư vấn miễn phí: <strong>0917 311 001</strong></p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>