<div class="bg_white home_sanpham_right">
    <div class="show2"> 
        <div class="content _tab-01 tab_link-01_01"> 
            <ul>
             <?php
             foreach ($this->Items as $key =>$val){ 
             ?>  
                <li class="sp_pro relative hover" data-id="<?php echo $key?>">
                    <div class="khung relative">
                        <div class="ttprod">
                            <div class="float_l chitiet"><a href=""><span>Chi tiết</span></a></div>
                            <div class="bg_comparison_tr"><span id="ss_70095598_0" class="myicon btn-ss">So sánh</span></div>
                        </div>
                        <a href="" class="bnc_tooltips">
                            <img src="<?php echo $this->baseUrl('public/files/products/images450x450/') . $val['picture'] ?>" alt="Tên Sản Phẩm">
                        </a>
                    </div>
                    <div class="thongtin">
                        <h3><a id="tenss_70095598" class="ten_sp tip" title="<?php echo $val['name'] ?>" ref=""><?php echo $val['name'] ?></a></h3> 
                            <?php
                            if($val['selloff'] > 0){
                                echo '<p class="gia_cu">'.number_format($val['price'],0).' VNĐ</p>';
                                $percent = ($val['price'] - $val['selloff']) * 100 / $val['selloff'];
                                echo '<div class="product-card__sale">-'. round($percent).' %</div>';
                                echo '<p class="gia_moi">'.number_format($val['selloff'],0) .'VNĐ</p>';
                            }
                            else
                                echo '<p class="gia_moi" style="margin-top: -15px">'.number_format($val['price'],0) .'VNĐ</p>';
                            ?>
                        <div class="clear"></div>
                    </div>
                    <div class="btn-function">
                        <div class="btnxemnhanh">
                            <a id="id_70095598" href="" title="Xem nhanh">
                                <span class="xemnhanh">Xem nhanh</span>
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </a>
                        </div>
                        <div id="ss_70095598_0" class="myicon btn-ss btnxemnhanh" title="So sánh">
                            <a id="id_70095598" href="" title="Xem nhanh">
                                <span>So sánh</span>
                                <i class="glyphicon glyphicon-transfer"></i>
                            </a>
                        </div>
                    </div>
                    <a href="<?php echo $this->baseUrl($val['alias'].'-'. $val['id']. '.html') ?>">
                        <div class="info info-<?php echo $key?>" style="display:none">
                            <span>
                                Mã sản phẩm: <?php echo $val['code']?><br>	
                                Nhà sản xuất: <?php echo $val['publisher']?><br>	
                                Số lần xem: <?php echo $val['hits']?><br>			
                                Bảo hành: <?php echo $val['warranty']?> <br>
                            </span>
                        </div>
                    </a>
                </li>   
             <?php
             }
             ?>
    
            </ul>  
            
            <div>
                <?php 
                    $currentUrl = $this->baseUrl($this->currentController . '/Index');
                    echo $this->paginationControl($this->paninator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                ?>

            </div>
            
            
        </div>
    </div>
    <div class="clear"></div>
</div>
<script>
    $(function() {
        $("input[name=price-order],input[name=warranty],input[name='price'],input[name='promotion[]'],input[name='product[]'],input[name='manufacturer[]']").click(function(){
            var priceFilter = $("input[name=price-order]:checked").val();
            var prices = $("input[name='price']:checked").val();
            var warranty = $("input[name='warranty']:checked").val();
            var id = '<?php echo $this->arrParam['id']?>';
            var manufacturer = '';
            var product = '';
            var promotion = '';
            // su dung vong lap de them gia tri checkbox vao chuoi....
            $("input[name='manufacturer[]']:checked").each(function(){
                manufacturer = manufacturer + ',' + $(this).val();
            });
            $("input[name='product[]']:checked").each(function(){
                product = product + ',' + $(this).val();
            });
            $("input[name='promotion[]']:checked").each(function(){
                promotion = promotion + ',' + $(this).val();
            });
            if(manufacturer.length>1){
                manufacturer = manufacturer.substring(1);
            }
            if(product.length>1){
                product = product.substring(1);
            }
            if(promotion.length>1){
                promotion = promotion.substring(1);
            }
            jQuery.ajax({
                url:"default/category/filter-ajax",
                type:"post",
                data:{
                    id : id,
                    manufacturer : manufacturer,
                    priceOrder: priceFilter,
                    priceFilter : prices,
                    promotion: promotion,
                    warranty: warranty,
                    product : product
                },
                async: true,
                cache: false,
                success: function(data){
                    $('.home_sanpham_right').html(data);
                }
            });
        });
    });
</script>