<?php 
	$title 		= $this->formText('title',$this->Item['title'],array('class'=>'txtmedium'));
	
	$content		= $this->cmsReplaceString($this->Item['content']);
	$content		= $this->cmsEditor('content',$content,array('toolbar'=>'Default','language'=>'vi'));
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$status 	= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	$order 		= $this->formText('order',$this->Item['order'],array('class'=>'txtshort'));	
	$inputInfo 		= array('name'=>'picture');
	$Input 		= array(
						array('Label'=>$this->translate('Title'),'input'=>$title,'info'=>0),
						array('Label'=>$this->translate('Content'),'input'=>$content,'style'=>'margin-left:174px'),
						array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
						array('Label'=>$this->translate('Order'),'input'=>$order,'info'=>0),
						);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>								
								<?php echo $this->partialLoop('rows.php',$Input) .$current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>