<?php 
	$title 				= $this->formText('title',$this->Item['title'],array('class'=>'txtmedium'));
	$phone				= $this->formText('phone',$this->Item['phone'],array('class'=>'txtmedium'));
	$fax				= $this->formText('fax',$this->Item['fax'],array('class'=>'txtmedium'));
	$tax_code			= $this->formText('code',$this->Item['code'],array('class'=>'txtmedium'));
	$hotline			= $this->formText('hotline',$this->Item['hotline'],array('class'=>'txtmedium'));
	$email				= $this->formText('email',$this->Item['email'],array('class'=>'txtmedium'));
	$yahoo				= $this->formText('yahoo',$this->Item['yahoo'],array('class'=>'txtmedium')) . '<span style="color: #666">  (nick-yahoo-1, nick-yahoo-2 ...)</span>';
	$skype				= $this->formText('skype',$this->Item['skype'],array('class'=>'txtmedium')). '<span style="color: #666">  (nick-skype-1, nick-skype-2 ...)</span>';
	$website			= $this->formText('website',$this->Item['website'],array('class'=>'txtmedium'));
	$alias 				= $this->formText('alias',$this->Item['alias'],array('class'=>'txtmedium'));
	$address 			= $this->formTextarea('address',str_replace('\\', '', $this->Item['address']),array('rows'=>'5'));
	$picture 			= $this->formFile('picture',array('style'=>'width: 250px'));								
	$content			= $this->cmsReplaceString($this->Item['content']);
	$content			= $this->cmsEditor('content',$content,array('toolbar'=>'Default','language'=>'vi'));
	
	$options 	= array($this->translate('Inactive'),$this->translate('Active'));
	$valSta 	= $this->Item['status'];
	if($valSta == ''){$valSta = 0;}
	$status 	= $this->formRadio('status',$valSta,null,$options, ' ');
	
	$options 	= array($this->translate('No'),$this->translate('Yes'));
	$featured 	= $this->formRadio('featured',$this->Item['featured'],null,$options, ' ');
	/*...........Picture............*/
	if(!empty($this->Item['picture'])){
	  	$urlimage   = FILES_URL . '/contact/images100x100/'. $this->Item['picture'];
	  	$imgimage  = '<span><img src="' . $urlimage . '" width="" height="40"></span>'; 
	  	$picture  = $imgimage ."<br/>" . $this->formFile('picture',array('style'=>'margin-left:173px'));	
	}else{
		$picture  = $this->formFile('picture',array('style'=>'margin-left:5px'));
	}
 	$current_stadium = $this->formHidden('current_stadium_picture',$this->Item['picture']);  
	
	$Input = array(
					array('Label'=>$this->translate('Title'),'input'=>$title,'info'=>0),
					array('Label'=>$this->translate('Alias'),'input'=>$alias,'info'=>0),
					array('Label'=>$this->translate('Phone'),'input'=>$phone,'info'=>0),
					array('Label'=>$this->translate('Fax'),'input'=>$fax,'info'=>0),
					array('Label'=>$this->translate('Tax code'),'input'=>$tax_code,'info'=>0),
					array('Label'=>$this->translate('Hot line'),'input'=>$hotline,'info'=>0),
					array('Label'=>$this->translate('Email'),'input'=>$email,'info'=>0),
					array('Label'=>$this->translate('Yahoo'),'input'=>$yahoo,'info'=>0),
					array('Label'=>$this->translate('Skype'),'input'=>$skype,'info'=>0),
					array('Label'=>$this->translate('Website'),'input'=>$website,'info'=>0),
					array('Label'=>$this->translate('Address'),'input'=>$address,'info'=>0),
					array('Label'=>$this->translate('Picture'),'input'=>$picture,'info'=>0),
					array('Label'=>$this->translate('Status'),'input'=>$status,'info'=>0),
					array('Label'=>$this->translate('Featured'),'input'=>$featured,'info'=>0),
					array('Label'=>$this->translate('Note'),'input'=>$content,'style'=>'margin-left:174px'),
					);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader"><?php echo $this->translate('Information')?></div>								
								<?php echo $this->partialLoop('rows.php',$Input) . $current_stadium ;?>                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>