<?php
	$val 			= $this->Item;
	$product_name  	= $val['name_pro'];
	$price			= $val['pro_pri'];
	$quantity  		= $val['quantity'];
	$to_money		= $price * $quantity;
											
	if(!empty($val['val_sell_pri']) || $val['val_sell_pri'] != 0){
		$val_sell_pro 	= $val['val_sell_pri'];
		$sale_pro 	= $val['selloff_pri'];
		$to_money	= $sale_pro * $quantity;
	}
											
	if((!empty($val['val_sell_pro']) || $val['val_sell_pro'] != 0) && (empty($val['val_sell_pri']) || $val['val_sell_pri'] == 0)){
		$val_sell_pro 	= $val['val_sell_pro'];
    	$sale_pro 		= $val['pro_pri'] - ($val['pro_pri'] * $val_sell_pro/100);
      	$to_money	= $sale_pro * $quantity;
	}
											
	if((empty($val['val_sell_pro']) || $val['val_sell_pro'] == 0) && (empty($val['val_sell_pri']) || $val['val_sell_pri'] == 0)){
		if(!empty($val['sale_off_menu'])){
			$val_sell_pro 	= $val['sale_off_menu'] ;
			$sale_pro 		= $val['pro_pri'] - ($val['pro_pri'] * $val_sell_pro/100);
			$to_money	= $sale_pro * $quantity;
		}
	}
											
	$full_name  	= $val['full_name'];
	$email  		= $val['email'];
	$phone  		= $val['phone'];
	$address  		= $val['address'];
	$shipping  		= $val['shipping'];
	$created  		= $val['created'];
	$comment  		= $val['comment'];
	
	/*...........Picture............*/
  	$urlimage   = FILES_URL . '/products/images100x100/'. $this->Item['picture'];
  	$picture  = '<img src="' . $urlimage . '" width="" height="40">'; 	
	$Input = array(
					array('Label'=>$this->translate('Product name'),'input'=>$product_name,'info'=>1),
					array('Label'=>$this->translate('Quantity'),'input'=>$quantity,'info'=>1),
					array('Label'=>$this->translate('Price'),'input'=>$price,'info'=>1),
					array('Label'=>$this->translate('Sale Off'),'input'=>$sale_pro,'info'=>1),
					array('Label'=>$this->translate('Total Money'),'input'=>$to_money,'info'=>1),
					array('Label'=>$this->translate('Guest'),'input'=>$full_name,'info'=>1),
					array('Label'=>$this->translate('Email'),'input'=>$email,'info'=>1),
					array('Label'=>$this->translate('Phone'),'input'=>$phone,'info'=>1),
					array('Label'=>$this->translate('Address'),'input'=>$address,'info'=>1),
					array('Label'=>$this->translate('Created'),'input'=>$created,'info'=>1),
					array('Label'=>$this->translate('Content'),'input'=>$comment,'info'=>1),
					);
	if(count($this->errors)>0){
		$errors = $this->formErrors($this->errors,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">

                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>
                        <?php echo $errors;?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Product name')?></div>
									<div>
										<span class="infor_item"><?php echo $product_name?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Quantity')?></div>
									<div>
										<span class="infor_item"><?php echo $quantity?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Price')?></div>
									<div>
										<span class="infor_item"><?php echo $price?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Sale Off')?></div>
									<div>
										<span class="infor_item"><?php echo $sale_pro?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Total Money')?></div>
									<div>
										<span class="infor_item"><?php echo $to_money?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Guest')?></div>
									<div>
										<span class="infor_item"><?php echo $full_name?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Email')?></div>
									<div>
										<span class="infor_item"><?php echo $email?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Phone')?></div>
									<div>
										<span class="infor_item"><?php echo $phone?></span>
									</div>	
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Address')?></div>
									<div class='cnt-info'>
										<span class="infor_item"><?php echo $address?></span>
									</div>
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Shipping')?></div>
									<div class='cnt-info'>
										<span class="infor_item"><?php echo $shipping?></span>
									</div>
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Content')?></div>
									<div class='cnt-info'>
										<span class="infor_item"><?php echo $comment?></span>
									</div>
								</div>
								<div id="row">
									<div class="label"><?php echo $this->translate('Created')?></div>
									<div>
										<span class="infor_item"><?php echo $created?></span>
									</div>	
								</div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>