<?php
	$id = $this->arrParam['cid'] ;
	$id_pro	= 'pro_' . $id;
?>
<div class="right width-75 float-right">
	<div class="group width-100">
	                        <div class="sub-right width-100">
	                        	<a class='active cat_pro_<?php echo $id?>' href="#"><?php echo $this->Title?></a>
	                        </div>
	                        <?php
	                        	$items	= $this->Items;
	                        	if(!empty($items)){
	                        ?>
	                        <div class="cnt-right mar-top-5 width-100">
	                        <?php
	                        	foreach ($items as $key => $value){
	                        			$cutTring 	= new Zendvn_File_CutTring();
	                    				$name		= str_replace("\\","",$value['name']);
//	                    				$name		= $cutTring->cutTring(50, $name, null);
	                    				
	                    				$alt		= str_replace("\\","",$value['alt_seo']);
	                    				if(!empty($value['alt_seo'])) $alt = str_replace("\\","",$value['name']);
	                    				
					            		$summary	= str_replace("\\","",$value['summary']);
					            		$summary	= $cutTring->cutTring(120, $summary, null);
					            		$menu_id	= $value['menu_id'];
					            		if(!empty($value['picture'])){
										    $linkImg	= FILES_URL . '/products/images450x450/' . $value['picture'];
										    $picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
									    }else{
										    $linkImg	= $this->imgUrl . '/no-image.jpg';
										    $picture 	= '<img title="'. $value['name'] .'" src="'. $linkImg .'" alt="'. $alt .'" />';
									    }
	                    				$lang = $this->arrParam['lang'];
					                    if(empty($lang)){
					                    	$lang = 'vi';
					                    }else{
					                    	$lang = $this->arrParam['lang'];
					                    }
										$urlOptions = array('module'=>'collections','controller'=>'index',
																			'action'=>'detail',
																			'tcat'=>$value['alias_name'],
																			'title'=>$value['alias'],
						                    								'cid'=> $value['menu_id'],
																			'id'=>$value['id'],
						                    								'lang'=>$lang);
						                $linkDetail = $this->url($urlOptions,'collections-detail');
						                $num = '';
						                if(($key+1)%4 == 0)$num = 'num-4';
	                        ?>
	                        	<div class="box width-21 <?php echo $num?>">
	                            	<div class="cnt-box box-col">
	                                	<div class="bor-img">
	                                    	<a href="<?php echo $linkDetail?>"><?php echo $picture?></a>
	                                    </div>
	                                    <div class="desc">
	                                    	<h2><a title="<?php echo str_replace("\\","",$value['name'])?>" href="<?php echo $linkDetail?>"><?php echo $name?></a></h2>
	                                    </div>
	                                </div>
	                            </div>
	                            <?php 
	                        		}
	                        	?>
	                        	<!--..........curent_page............ -->
		                        <div class="clear cur-page mar-top-10 float-left">
							        <?php
							        	$paginator = $this->arrParam['paginator'];
										$itemCountPerPage = $paginator['itemCountPerPage'];
			                        	if($this->total > $itemCountPerPage){
			                        		$currentUrl = $this->baseUrl($this->currentController . '/index');
			                        		echo $this->paginationControl($this->panigator,'Sliding','curentpage.phtml',array('currentUrl'=>$currentUrl,'arrParam'=>$this->arrParam));
			                        	}
			                        ?>
							    </div>
								<!--..........curent_page............-->
	                        </div>
	                        <?php
	                        	} 
	                        ?>
	                    </div>
</div>