<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$langTmp = $ssFilter['lang'];
	$lang = '';
	if(!empty($langTmp)){
		$lang = '/lang/' . $langTmp;
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$tblCode 		= $this->cmsLinkSort($this->translate('Code product'),'p.code_pro',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	$tblSize 		= $this->cmsLinkSort($this->translate('Size'),'p.Size',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$tblId 		= $this->cmsLinkSort('ID','id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now',$this->translate('Search'),
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords',$this->translate('Clear'),
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;
?>
<form name="appForm" method="post" action="">
                        <?php echo $this->render('toolbar.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('sublink.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php echo $strSearch;?>
									</div>
								</div>	
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th width="350"><?php echo $tblCode ?></th>
                                            <th width="350"><?php echo $tblSize?></th>
                                            <th width="350"><?php echo $this->translate('Units')?></th>
                                            <th width="150"><?php echo $this->translate('Price') . ' (VND)'?></th>
                                            <th width="250"><?php echo $this->translate('Sale Off') . ' (VND)' ?></th>
                                            <th width="200"><?php echo $this->translate('Sale off (%)')?></th>
                                            <th width="200"><?php echo $this->translate('Status')?></th>
                                            <th width="150">Control</th>
                                            <th width="100"><?php echo $tblId?></th>
                                        </tr>
                                    </thead>
									<?php
										foreach($this->Items as $key => $val){
											$code 		= $val['code_pro'];
											if($val['unit_name'] == 1) $unit_name = 'Meters';
											if($val['unit_name'] == 2) $unit_name = 'Centimeters';
											if($val['unit_name'] == 3) $unit_name = 'Millimeters';
											$size 		= $val['size'];
											$price 		= number_format($val['price'],0);
											$selloff 	= number_format($val['selloff'],0);
											$val_sell 	= $val['val_sell'];
											$size 		= $val['size'];
											$id 		= $val['id'];
											$status 	= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												$status = $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive', $linkStatus, $id);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status = $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active', $linkStatus, $id);
											}
											
											$options1 	= array(
												$this->translate('Select a units'),
												$this->translate('Meters'),
												$this->translate('Centimeters'),
												$this->translate('Millimeters'),
											);
											$units	= $this->formSelect('units['.$id.']',$val['units'],null,$options1,null);
											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $lang);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $lang);
											$btnDelete =  $this->cmsAjaxButton('ajax-delete-item', 'Delete Item', 'Delete', $linkDelete, $id);
										
											$strIconButton	= $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
											$cls = 'row0';
											if($key%2 == 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="<?php echo $cls?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><a href="<?php echo $linkEdit?>"><?php echo $code?></a></td>
                                        <td align="center"><?php echo $size?></td>
                                        <td align="center"><?php echo $unit_name?></td>
                                        <td align="center"><?php echo $price?></td>
                                        <td style='font-weight: bold;color: red' align="center"><?php echo $selloff?></td>
                                        <td style='font-weight: bold;color: red' align="center"><?php echo $val_sell?></td>
                                        <td align="center"><?php echo $status;?></td>                               
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->
								
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>