<?php 
        //1. Active Items - submit
	$linkActiveItems = $this->baseUrl($this->currentController . '/status/type/1' . $lang);
	$btnActiveItems = $this->cmsButton($this->translate('Active'),$linkActiveItems,
										$this->imgUrl . '/toolbar/icon-32-active.png','submit');
	//2. Inactive Items - submit										
	$linkInactiveItems = $this->baseUrl($this->currentController . '/status/type/0' . $lang);
	$btnInactiveItems = $this->cmsButton($this->translate('Inactive'),$linkInactiveItems,
										$this->imgUrl . '/toolbar/icon-32-inactive.png','submit');
        //5. Delete Items - submit	
	$linkDeleteItems = $this->baseUrl($this->currentController . '/multi-delete' . $lang);
	$btnDeleteItems = $this->cmsButton($this->translate('Delete'),$linkDeleteItems,
										$this->imgUrl . '/toolbar/icon-32-delete.png','submit');
        $strBtn = $btnActiveItems . ' ' . $btnInactiveItems . '  ' . $btnDeleteItems;
//?>
<form name="appForm" method="post" action="">
    <div id="toolbar-box">
        <div class="t"><div class="t"><div class="t"></div></div></div>
        <div class="m">
            <div id="toolbar" class="toolbar" >				
                <?php
                echo $strBtn;
                ?>
                <div class="clr"></div>
            </div>
            <div class="header icon-48-install"><?php echo $this->Title; ?></div>

            <div class="clr"></div>
        </div>
        <div class="b"><div class="b"><div class="b"></div></div></div>
    </div>
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php //echo $strSearch;?>
									</div>
								</div>	
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th>Phone</th>
                                            <th width="83">NgayTuVan</th>
                                            <th width="83">Status</th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$phone	= $val['phone'];
											
											$ngaygiotuvan 		= $val['ngaygiotuvan'];
											$status 		= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												$status 	= $this->cmsAjaxButton('ajax-active-item', 'Active', 'Inactive *'. $phone . '*', $linkStatus, $id);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status 	= $this->cmsAjaxButton('ajax-inactive-item', 'Inactive', 'Active *'. $phone . '*', $linkStatus, $id);
											}
                                                                                        $cid			= $this->formCheckbox('cid[]',$val['id']);
											$cls = 'row0';
											if($key%2 != 0){
												$cls = 'row1';
											}
									?>
                                    <tr class="even <?php echo $cls;?>">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $phone;?></a></td>
                                        <td align="center"><?php echo $ngaygiotuvan;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>